/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistock;

import java.awt.Color;
import static java.awt.Frame.MAXIMIZED_BOTH;
import javax.swing.JOptionPane;

/**
 *
 * @author ruben
 */
public class frm_servicio extends javax.swing.JFrame {

    /**
     * Creates new form frm_servicio
     */
    public frm_servicio() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.WHITE);
        this.setTitle("SISTOCK - SERVICIO");
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radio_servicio = new javax.swing.ButtonGroup();
        lbl_encabezadocc = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_servicio = new javax.swing.JTable();
        bot_cerrar = new javax.swing.JButton();
        bot_limpiar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        radio_crearservicio = new javax.swing.JRadioButton();
        lbl_deservicio = new javax.swing.JLabel();
        txt_servicio = new javax.swing.JTextField();
        bot_crear = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        radio_actualizarservicio = new javax.swing.JRadioButton();
        lbl_desnuevoservicio = new javax.swing.JLabel();
        lbl_nuevaservicio = new javax.swing.JLabel();
        cmb_servicio = new javax.swing.JComboBox();
        txt_nuevaservicio = new javax.swing.JTextField();
        bot_actualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_encabezadocc.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbl_encabezadocc.setForeground(new java.awt.Color(0, 0, 255));
        lbl_encabezadocc.setText("MÓDULO DE SERVICIOS");
        getContentPane().add(lbl_encabezadocc, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, -1));

        jScrollPane2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        table_servicio.setBackground(new java.awt.Color(240, 255, 255));
        table_servicio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        table_servicio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CÓDIGO", "DESCRIPCIÓN"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(table_servicio);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 640, 180));

        bot_cerrar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bot_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/close.png"))); // NOI18N
        bot_cerrar.setText("CERRAR");
        bot_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_cerrarActionPerformed(evt);
            }
        });
        getContentPane().add(bot_cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 650, -1, -1));

        bot_limpiar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bot_limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eraser.png"))); // NOI18N
        bot_limpiar.setText("REINICIAR");
        bot_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_limpiarActionPerformed(evt);
            }
        });
        getContentPane().add(bot_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 650, -1, -1));

        jPanel1.setBackground(new java.awt.Color(240, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        radio_crearservicio.setBackground(new java.awt.Color(240, 255, 255));
        radio_servicio.add(radio_crearservicio);
        radio_crearservicio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        radio_crearservicio.setSelected(true);
        radio_crearservicio.setText("CREAR SERVICIO");
        radio_crearservicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_crearservicioActionPerformed(evt);
            }
        });
        jPanel1.add(radio_crearservicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        lbl_deservicio.setBackground(new java.awt.Color(240, 255, 255));
        lbl_deservicio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_deservicio.setText("DESCRIPCIÓN SERVICIO");
        jPanel1.add(lbl_deservicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        txt_servicio.setBackground(new java.awt.Color(240, 255, 255));
        txt_servicio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txt_servicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 300, -1));

        bot_crear.setBackground(new java.awt.Color(240, 255, 255));
        bot_crear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bot_crear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/databasesave.png"))); // NOI18N
        bot_crear.setText("CREAR");
        bot_crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_crearActionPerformed(evt);
            }
        });
        jPanel1.add(bot_crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 40, 170, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 850, 80));

        jPanel2.setBackground(new java.awt.Color(240, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        radio_actualizarservicio.setBackground(new java.awt.Color(240, 255, 255));
        radio_servicio.add(radio_actualizarservicio);
        radio_actualizarservicio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        radio_actualizarservicio.setText("ACTUALIZAR SERVICIO");
        radio_actualizarservicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_actualizarservicioActionPerformed(evt);
            }
        });
        jPanel2.add(radio_actualizarservicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        lbl_desnuevoservicio.setBackground(new java.awt.Color(240, 255, 255));
        lbl_desnuevoservicio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_desnuevoservicio.setText("SERVICIO");
        jPanel2.add(lbl_desnuevoservicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        lbl_nuevaservicio.setBackground(new java.awt.Color(240, 255, 255));
        lbl_nuevaservicio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_nuevaservicio.setText("NUEVA DESCRIPCIÓN SERVICIO");
        jPanel2.add(lbl_nuevaservicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        cmb_servicio.setBackground(new java.awt.Color(240, 255, 255));
        cmb_servicio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmb_servicio.setEnabled(false);
        cmb_servicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_servicioActionPerformed(evt);
            }
        });
        jPanel2.add(cmb_servicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 300, -1));

        txt_nuevaservicio.setBackground(new java.awt.Color(240, 255, 255));
        txt_nuevaservicio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_nuevaservicio.setEnabled(false);
        txt_nuevaservicio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nuevaservicioKeyPressed(evt);
            }
        });
        jPanel2.add(txt_nuevaservicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 300, -1));

        bot_actualizar.setBackground(new java.awt.Color(240, 255, 255));
        bot_actualizar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bot_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/refresh.png"))); // NOI18N
        bot_actualizar.setText("ACTUALIZAR");
        bot_actualizar.setEnabled(false);
        bot_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_actualizarActionPerformed(evt);
            }
        });
        jPanel2.add(bot_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 850, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bot_crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_crearActionPerformed
        String sql;
        boolean resp;
        
        if(!txt_servicio.getText().equals("")) {

                servicio ser = new servicio(txt_servicio.getText().trim().toUpperCase(),2);

                resp = ser.actualizar_servicio();
                
                if (resp){
                   ser.consulta_servicio(table_servicio);
                   sql="select id_servicio,descripcion from tbl_servicio;";       
                   cmb_servicio = funciones.cargar_combo(cmb_servicio,sql,txt_servicio.getText().toUpperCase().trim());
                   

                   txt_servicio.setText("");
                   
                }
                
        }
        else{
            JOptionPane.showMessageDialog(null,"DATOS INCOMPLETOS PARA GUARDAR");
        }
    }//GEN-LAST:event_bot_crearActionPerformed

    private void bot_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_cerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_bot_cerrarActionPerformed

    private void radio_crearservicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_crearservicioActionPerformed
        txt_servicio.setEnabled(true);
        bot_crear.setEnabled(true);
        cmb_servicio.setEnabled(false);
        txt_nuevaservicio.setEnabled(false);
        bot_actualizar.setEnabled(false);
        txt_servicio.requestFocusInWindow();
    }//GEN-LAST:event_radio_crearservicioActionPerformed

    private void radio_actualizarservicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_actualizarservicioActionPerformed
        txt_servicio.setText("");
        txt_servicio.setEnabled(false);
        bot_crear.setEnabled(false);
        cmb_servicio.setEnabled(true);
        txt_nuevaservicio.setEnabled(true);
        bot_actualizar.setEnabled(true);
            
    }//GEN-LAST:event_radio_actualizarservicioActionPerformed

    private void bot_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_actualizarActionPerformed
        boolean resp = true;
        String sql;
         
        
        if(!txt_nuevaservicio.getText().equals("") && !cmb_servicio.getSelectedItem().equals("Seleccione...") ) {

                           
                servicio ser = new servicio(txt_nuevaservicio.getText().trim().toUpperCase(),2);
                
                resp = ser.buscar_idservicio();
                
           
            
            if (resp){
                 ser = new servicio(Integer.parseInt(cmb_servicio.getSelectedItem().toString().substring(0,3).trim()),txt_nuevaservicio.getText().trim().toUpperCase(),3);

                resp = ser.actualizar_servicio_detalle();

                if (resp){
                    ser.consulta_servicio(table_servicio);
                    
                    sql="select id_servicio,descripcion from tbl_servicio;";       
        
                    cmb_servicio = funciones.cargar_combo(cmb_servicio,sql,txt_nuevaservicio.getText().trim().toUpperCase());
                    
                    txt_nuevaservicio.setText("");
                    
                }
            }
        }
        else{

            JOptionPane.showMessageDialog(null,"DATOS INCOMPLETOS PARA ACTUALIZAR");
        }
    }//GEN-LAST:event_bot_actualizarActionPerformed

    private void bot_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_limpiarActionPerformed
        txt_servicio.setText("");
        bot_crear.setEnabled(true);
        cmb_servicio.setEnabled(false);
        txt_nuevaservicio.setText("");
        bot_actualizar.setEnabled(false);
        radio_actualizarservicio.setSelected(false); 
    }//GEN-LAST:event_bot_limpiarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        String sql;
        
        servicio cc = new servicio();
        cc.consulta_servicio(table_servicio);
        
        txt_servicio.requestFocusInWindow();
        
        
        sql="select id_servicio,descripcion from tbl_servicio;";       
        
        cmb_servicio = funciones.cargar_combo(cmb_servicio,sql,"Seleccione...");
    }//GEN-LAST:event_formWindowOpened

    private void txt_nuevaservicioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nuevaservicioKeyPressed
       if (evt.getKeyCode()==10){
            bot_actualizar.doClick();
        }
        
        if (evt.getKeyCode() == 27){
         
            bot_limpiar.doClick();
                    
        }
    }//GEN-LAST:event_txt_nuevaservicioKeyPressed

    private void cmb_servicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_servicioActionPerformed
        
        if(evt.getModifiers() != 0){
            if (cmb_servicio.getSelectedItem().equals("Seleccione...")){
                txt_nuevaservicio.setText("");
            }
            else{
                txt_nuevaservicio.setText(cmb_servicio.getSelectedItem().toString().substring(4,cmb_servicio.getSelectedItem().toString().length()).trim());
            }
        }
        
    }//GEN-LAST:event_cmb_servicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_servicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_servicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_servicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_servicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_servicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bot_actualizar;
    private javax.swing.JButton bot_cerrar;
    private javax.swing.JButton bot_crear;
    private javax.swing.JButton bot_limpiar;
    private javax.swing.JComboBox cmb_servicio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_deservicio;
    private javax.swing.JLabel lbl_desnuevoservicio;
    private javax.swing.JLabel lbl_encabezadocc;
    private javax.swing.JLabel lbl_nuevaservicio;
    private javax.swing.JRadioButton radio_actualizarservicio;
    private javax.swing.JRadioButton radio_crearservicio;
    private javax.swing.ButtonGroup radio_servicio;
    private javax.swing.JTable table_servicio;
    private javax.swing.JTextField txt_nuevaservicio;
    private javax.swing.JTextField txt_servicio;
    // End of variables declaration//GEN-END:variables
}
