/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistock;

import java.awt.Color;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.sql.SQLException;

import javax.swing.JOptionPane;

/**
 *
 * @author ruben
 */
public class frm_tasa extends javax.swing.JFrame {

    /**
     * Creates new form frm_tasa
     */
    public frm_tasa() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.WHITE);
        String sql;
        this.setTitle("SISTOCK - TASA DE CAMBIO");
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_idtasa = new javax.swing.JTextField();
        lbl_tasa = new javax.swing.JLabel();
        lbl_mes = new javax.swing.JLabel();
        lbl_ano = new javax.swing.JLabel();
        spin_ano = new javax.swing.JSpinner();
        txt_tasa = new javax.swing.JTextField();
        cmb_mes = new javax.swing.JComboBox<>();
        bot_guardar = new javax.swing.JButton();
        bot_reiniciar = new javax.swing.JButton();
        bot_actualizar = new javax.swing.JButton();
        bot_cerrar = new javax.swing.JButton();
        lbl_fecjadesde = new javax.swing.JLabel();
        lbl_fechahasta = new javax.swing.JLabel();
        date_desde = new com.toedter.calendar.JDateChooser();
        date_hasta = new com.toedter.calendar.JDateChooser();
        lbl_encabezadocc = new javax.swing.JLabel();

        txt_idtasa.setText("0");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_tasa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_tasa.setText("TASA(Bs)");
        getContentPane().add(lbl_tasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 340, -1, -1));

        lbl_mes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_mes.setText("MES");
        getContentPane().add(lbl_mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, -1, -1));

        lbl_ano.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_ano.setText("AÑO");
        getContentPane().add(lbl_ano, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, -1, -1));

        spin_ano.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        spin_ano.setModel(new javax.swing.SpinnerNumberModel(2017, 2017, null, 1));
        spin_ano.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spin_anoStateChanged(evt);
            }
        });
        getContentPane().add(spin_ano, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 180, -1, 30));

        txt_tasa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_tasa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_tasaKeyPressed(evt);
            }
        });
        getContentPane().add(txt_tasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 330, 120, 30));

        cmb_mes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cmb_mes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "1  -  ENERO", "2  -  FEBRERO", "3  -  MARZO", "4  -  ABRIL", "5  -  MAYO", "6  -  JUNIO", "7  -  JULIO", "8  -  AGOSTO", "9  -  SEPTIEMBRE", "10 -  OCTUBRE", "11 -  NOVIEMBRE", "12 -  DICIEMBRE" }));
        cmb_mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_mesActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 130, 200, 30));

        bot_guardar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bot_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/databasesave.png"))); // NOI18N
        bot_guardar.setText("GUARDAR");
        bot_guardar.setEnabled(false);
        bot_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_guardarActionPerformed(evt);
            }
        });
        getContentPane().add(bot_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 480, -1, -1));

        bot_reiniciar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bot_reiniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eraser.png"))); // NOI18N
        bot_reiniciar.setText("REINICIAR");
        bot_reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_reiniciarActionPerformed(evt);
            }
        });
        getContentPane().add(bot_reiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 480, -1, -1));

        bot_actualizar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bot_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/refresh.png"))); // NOI18N
        bot_actualizar.setText("ACTUALIZAR");
        bot_actualizar.setEnabled(false);
        bot_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_actualizarActionPerformed(evt);
            }
        });
        getContentPane().add(bot_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 480, -1, -1));

        bot_cerrar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bot_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/close.png"))); // NOI18N
        bot_cerrar.setText("CERRAR");
        bot_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_cerrarActionPerformed(evt);
            }
        });
        getContentPane().add(bot_cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 480, -1, -1));

        lbl_fecjadesde.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_fecjadesde.setText("FECHA DESDE");
        getContentPane().add(lbl_fecjadesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, -1, -1));

        lbl_fechahasta.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_fechahasta.setText("FECHA HASTA");
        getContentPane().add(lbl_fechahasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, -1, -1));

        date_desde.setDateFormatString("dd/MM/yyyy");
        date_desde.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(date_desde, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 220, 190, 30));

        date_hasta.setDateFormatString("dd/MM/yyyy");
        date_hasta.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(date_hasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 260, 190, 30));

        lbl_encabezadocc.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbl_encabezadocc.setForeground(new java.awt.Color(0, 0, 255));
        lbl_encabezadocc.setText("MÓDULO DE TASA DE CAMBIO $");
        getContentPane().add(lbl_encabezadocc, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_mesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_mesActionPerformed
        
     
        tasa modelo_tasa = null;
        
    
        
        if (evt.getModifiers() != 0){
       
            if(!cmb_mes.getSelectedItem().equals("Seleccione") /*&& !txt_tasa.getText().trim().equals("") && resp*/){
        
                tasa tas = new tasa(
                        0,
                        Integer.parseInt(cmb_mes.getSelectedItem().toString().substring(0, 3).trim()), 
                        Integer.parseInt(spin_ano.getValue().toString()), 
                        "", 
                        "", 
                        0, 
                        ""
        
                );
            
                try {
                    modelo_tasa = tas.buscar_tasa();
                    if (!modelo_tasa.getId_tasa().equals(0)){
                        funciones.fecha_convertir_string(modelo_tasa.getFechadesde(),date_desde);
                        funciones.fecha_convertir_string(modelo_tasa.getFechahasta(),date_hasta);
                        
                        bot_guardar.setEnabled(false);
                        bot_actualizar.setEnabled(true);
                                              
                        txt_tasa.setText(String.valueOf(modelo_tasa.getTasa()));
                        txt_idtasa.setText(String.valueOf(modelo_tasa.getId_tasa()));
                        
                    }
                    else{
                        date_desde.setDate(null);
                        date_hasta.setDate(null);
                        txt_tasa.setText("");
                        bot_guardar.setEnabled(true);
                        bot_actualizar.setEnabled(false);
                        txt_idtasa.setText("0");
                    }
                } 
                catch (SQLException ex) {}
               
            }
            else{
                bot_guardar.setEnabled(false);
                bot_actualizar.setEnabled(false);
            }
        }    
    }//GEN-LAST:event_cmb_mesActionPerformed

    private void bot_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_cerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_bot_cerrarActionPerformed

    private void bot_reiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_reiniciarActionPerformed
        frm_tasa frm = new frm_tasa();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bot_reiniciarActionPerformed

    private void bot_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_guardarActionPerformed
        String fechadesde=null;
        String fechahasta=null;
        Boolean resp = true;
        tasa modelo_tasa = null;
        
        try{
            fechadesde = funciones.fecha_convertir_date(date_desde, 1);
            fechahasta = funciones.fecha_convertir_date(date_hasta, 1);
        }
        catch(NullPointerException e){
            resp = false;
        }
       
       
            if(!cmb_mes.getSelectedItem().equals("Seleccione") && !txt_tasa.getText().trim().equals("") && resp){
        
                tasa tas = new tasa(
                        0,
                        Integer.parseInt(cmb_mes.getSelectedItem().toString().substring(0, 3).trim()), 
                        Integer.parseInt(spin_ano.getValue().toString()), 
                        fechadesde, 
                        fechahasta, 
                        Integer.parseInt(txt_tasa.getText()), 
                        frm_principal.nombre
        
                );
                
                              
                if (tas.guardar_tasa()){
                    bot_guardar.setEnabled(false);
                    bot_actualizar.setEnabled(true);
                }
            }    
            else{
                JOptionPane.showMessageDialog(null, "FALTAN DATOS POR COMPLETAR");
            }
            
    }//GEN-LAST:event_bot_guardarActionPerformed

    private void txt_tasaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_tasaKeyPressed
       if ( ( (evt.getKeyCode() >= 48 ) && (evt.getKeyCode() <= 57 ) ) || ( (evt.getKeyCode() >= 37 ) && (evt.getKeyCode() <= 40 ) ) || ((evt.getKeyCode() >= 96 ) && (evt.getKeyCode() <= 105 )) || (evt.getKeyCode() == 144) || (evt.getKeyCode() == 127) || (evt.getKeyCode() == 8)  || (evt.getKeyCode() == 10)){       
        }
        else{
            JOptionPane.showMessageDialog(null, "CARACTER NO VALIDO. SOLO NÚMEROS (1..9)", "SISTOCK - TASA DE CAMBIO $", JOptionPane.ERROR_MESSAGE,null);
            txt_tasa.setText("");
             
        }
    }//GEN-LAST:event_txt_tasaKeyPressed

    private void bot_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_actualizarActionPerformed
       String fechadesde=null;
        String fechahasta=null;
        Boolean resp = true;
        tasa modelo_tasa = null;
        
        
        
        try{
            fechadesde = funciones.fecha_convertir_date(date_desde, 1);
            fechahasta = funciones.fecha_convertir_date(date_hasta, 1);
        }
        catch(NullPointerException e){
            resp = false;
        }
       
        if(funciones.verificar_mes_autorizacion(Integer.parseInt(cmb_mes.getSelectedItem().toString().substring(0, 3).trim()), Integer.parseInt(spin_ano.getValue().toString()), "")){
            if(!cmb_mes.getSelectedItem().equals("Seleccione") && !txt_tasa.getText().trim().equals("") && resp){
        
                tasa tas = new tasa(
                        Integer.parseInt(txt_idtasa.getText()),
                        Integer.parseInt(cmb_mes.getSelectedItem().toString().substring(0, 3).trim()), 
                        Integer.parseInt(spin_ano.getValue().toString()), 
                        fechadesde, 
                        fechahasta, 
                        Integer.parseInt(txt_tasa.getText()), 
                        frm_principal.nombre
        
                );
                
                              
                if (tas.actualizar_tasa()){
                    bot_guardar.setEnabled(false);
                }
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "EL MES DE " + cmb_mes.getSelectedItem().toString().substring(4,cmb_mes.getSelectedItem().toString().length()).trim() + " ESTA CERRADO CONTABLEMENTE");
        }
    }//GEN-LAST:event_bot_actualizarActionPerformed

    private void spin_anoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spin_anoStateChanged
             tasa modelo_tasa = null;
        
    
        
        
       
            if(!cmb_mes.getSelectedItem().equals("Seleccione") /*&& !txt_tasa.getText().trim().equals("") && resp*/){
        
                tasa tas = new tasa(
                        0,
                        Integer.parseInt(cmb_mes.getSelectedItem().toString().substring(0, 3).trim()), 
                        Integer.parseInt(spin_ano.getValue().toString()), 
                        "", 
                        "", 
                        0, 
                        ""
        
                );
            
                try {
                    modelo_tasa = tas.buscar_tasa();
                    if (!modelo_tasa.getId_tasa().equals(0)){
                        funciones.fecha_convertir_string(modelo_tasa.getFechadesde(),date_desde);
                        funciones.fecha_convertir_string(modelo_tasa.getFechahasta(),date_hasta);
                        
                        bot_guardar.setEnabled(false);
                        bot_actualizar.setEnabled(true);
                                              
                        txt_tasa.setText(String.valueOf(modelo_tasa.getTasa()));
                        txt_idtasa.setText(String.valueOf(modelo_tasa.getId_tasa()));
                        
                    }
                    else{
                        date_desde.setDate(null);
                        date_hasta.setDate(null);
                        txt_tasa.setText("");
                        bot_guardar.setEnabled(true);
                        bot_actualizar.setEnabled(false);
                        txt_idtasa.setText("0");
                    }
                } 
                catch (SQLException ex) {}
               
            }
            else{
                bot_guardar.setEnabled(false);
                bot_actualizar.setEnabled(false);
            }
           
    }//GEN-LAST:event_spin_anoStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_tasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_tasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_tasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_tasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_tasa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bot_actualizar;
    private javax.swing.JButton bot_cerrar;
    private javax.swing.JButton bot_guardar;
    private javax.swing.JButton bot_reiniciar;
    private javax.swing.JComboBox<String> cmb_mes;
    private com.toedter.calendar.JDateChooser date_desde;
    private com.toedter.calendar.JDateChooser date_hasta;
    private javax.swing.JLabel lbl_ano;
    private javax.swing.JLabel lbl_encabezadocc;
    private javax.swing.JLabel lbl_fechahasta;
    private javax.swing.JLabel lbl_fecjadesde;
    private javax.swing.JLabel lbl_mes;
    private javax.swing.JLabel lbl_tasa;
    private javax.swing.JSpinner spin_ano;
    private javax.swing.JTextField txt_idtasa;
    private javax.swing.JTextField txt_tasa;
    // End of variables declaration//GEN-END:variables
}
