/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistock;

import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import javax.swing.JOptionPane;
import jxl.write.WriteException;

/**
 *
 * @author ruben
 */
public class frm_auditoria_tallerpkf extends javax.swing.JFrame {

    /**
     * Creates new form frm_auditoria_tallerpkf
     */
    public frm_auditoria_tallerpkf() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("SISTOCK - TRANSACCIONES TALLER PKG");
        this.getContentPane().setBackground(Color.WHITE);
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_auditoria = new javax.swing.JTable();
        bot_exportarexcel = new javax.swing.JButton();
        bot_cerrar = new javax.swing.JButton();
        lbl_encabezado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla_auditoria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tabla_auditoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_bitacora", "transaccion", "usuario", "fecha transaccion", "id solicitud", "cedula", "nombres", "equipo", "centro costo", "componente", "falla", "servicio", "observaciones", "fecha solicitud", "servicio pkf", "realizado por", "costo total", "fecha servicio", "estatus", "empresa entregado", "nombre entregado", "observacion entregado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla_auditoria);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 108, 1290, 470));

        bot_exportarexcel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bot_exportarexcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/excel.png"))); // NOI18N
        bot_exportarexcel.setText("EXPORTAR EXCEL");
        bot_exportarexcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_exportarexcelActionPerformed(evt);
            }
        });
        getContentPane().add(bot_exportarexcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 590, -1, -1));

        bot_cerrar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bot_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/close.png"))); // NOI18N
        bot_cerrar.setText("CERRAR");
        bot_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_cerrarActionPerformed(evt);
            }
        });
        getContentPane().add(bot_cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 590, -1, -1));

        lbl_encabezado.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbl_encabezado.setForeground(new java.awt.Color(0, 0, 255));
        lbl_encabezado.setText("TRANSACCIONES TALLER");
        getContentPane().add(lbl_encabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bot_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_cerrarActionPerformed
       this.dispose();  
    }//GEN-LAST:event_bot_cerrarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        auditoria audi = new auditoria(tabla_auditoria);
        
        audi.log_stock_tallerpkf();
    }//GEN-LAST:event_formWindowOpened

    private void bot_exportarexcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_exportarexcelActionPerformed
        String nombre_archivo;
        
        nombre_archivo = "C:/Documentos_Sistock/Auditoria_tallerpkf.xls";
        
        
        reporte_excel ex = new reporte_excel(new File(nombre_archivo), "LOG TALLER PKF", tabla_auditoria);
        
        
        try {
            if(ex.excel_export_auditoria_tallerpkf()){
                
                    File archivo_abrir = new File(nombre_archivo);
                    Desktop.getDesktop().open(archivo_abrir);
                
            }
            else{
                JOptionPane.showMessageDialog(null, "ERROR EN EXPORTAR ARCHIVO EXCEL");
            }
        } catch (IOException | WriteException ex1) {
            JOptionPane.showMessageDialog(null, "ERROR ABRIR ARCHIVO");
        }

    }//GEN-LAST:event_bot_exportarexcelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_auditoria_tallerpkf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_auditoria_tallerpkf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_auditoria_tallerpkf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_auditoria_tallerpkf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_auditoria_tallerpkf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bot_cerrar;
    private javax.swing.JButton bot_exportarexcel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_encabezado;
    private javax.swing.JTable tabla_auditoria;
    // End of variables declaration//GEN-END:variables
}
