/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistock;

import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import javax.swing.JOptionPane;
import jxl.write.WriteException;

/**
 *
 * @author ruben
 */
public class frm_reporte extends javax.swing.JFrame {

    /**
     * Creates new form frm_reporte
     */
    public frm_reporte() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.WHITE);
        this.setTitle("SISTOCK - INFORME DE GESTION");
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo_fecha = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_resumen = new javax.swing.JTable();
        grupo_informe = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        radio_rango = new javax.swing.JRadioButton();
        date_desde = new com.toedter.calendar.JDateChooser();
        date_hasta = new com.toedter.calendar.JDateChooser();
        radio_mes = new javax.swing.JRadioButton();
        cmb_mes = new javax.swing.JComboBox<>();
        radio_ano = new javax.swing.JRadioButton();
        cmb_ano = new javax.swing.JComboBox<>();
        cmb_anual = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        chk_costo = new javax.swing.JCheckBox();
        chk_centrocosto = new javax.swing.JCheckBox();
        cmb_centrocosto = new javax.swing.JComboBox<>();
        chk_equipo = new javax.swing.JCheckBox();
        cmb_equipo = new javax.swing.JComboBox<>();
        cmb_costo = new javax.swing.JComboBox<>();
        bot_excel = new javax.swing.JButton();
        bot_limpiar = new javax.swing.JButton();
        bot_cerrar = new javax.swing.JButton();
        lbl_informe = new javax.swing.JLabel();
        radio_detallado = new javax.swing.JRadioButton();
        radio_resumen = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();

        tabla_resumen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "sap", "descripcion", "costo", "cant_ume", "ume", "valor", "tasa_mes", "fecha", "id_equipo", "equipo", "cantrecib", "cantdisp", "cantidadsalida", "precio_unitario", "subtotal", "flete", "montototal", "estatus", "id_centrocosto", "centrocosto", "fleteNacAct", "fleteAct", "MontoTotalAct $", "fletebs"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla_resumen);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(240, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        radio_rango.setBackground(new java.awt.Color(240, 255, 255));
        grupo_fecha.add(radio_rango);
        radio_rango.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        radio_rango.setSelected(true);
        radio_rango.setText("RANGO DE FECHA");
        radio_rango.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_rangoActionPerformed(evt);
            }
        });
        jPanel1.add(radio_rango, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        date_desde.setBackground(new java.awt.Color(240, 255, 255));
        date_desde.setDateFormatString("dd/MM/yyyy");
        date_desde.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(date_desde, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 160, 30));

        date_hasta.setBackground(new java.awt.Color(240, 255, 255));
        date_hasta.setDateFormatString("dd/MM/yyyy");
        date_hasta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(date_hasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 160, 30));

        radio_mes.setBackground(new java.awt.Color(240, 255, 255));
        grupo_fecha.add(radio_mes);
        radio_mes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        radio_mes.setText("MES");
        radio_mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_mesActionPerformed(evt);
            }
        });
        jPanel1.add(radio_mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        cmb_mes.setBackground(new java.awt.Color(240, 255, 255));
        cmb_mes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmb_mes.setEnabled(false);
        cmb_mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_mesActionPerformed(evt);
            }
        });
        jPanel1.add(cmb_mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 160, 30));

        radio_ano.setBackground(new java.awt.Color(240, 255, 255));
        grupo_fecha.add(radio_ano);
        radio_ano.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        radio_ano.setText("ANUAL");
        radio_ano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_anoActionPerformed(evt);
            }
        });
        jPanel1.add(radio_ano, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        cmb_ano.setBackground(new java.awt.Color(240, 255, 255));
        cmb_ano.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmb_ano.setEnabled(false);
        jPanel1.add(cmb_ano, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 160, 30));

        cmb_anual.setBackground(new java.awt.Color(240, 255, 255));
        cmb_anual.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmb_anual.setEnabled(false);
        jPanel1.add(cmb_anual, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 160, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 630, 190));

        jPanel2.setBackground(new java.awt.Color(240, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chk_costo.setBackground(new java.awt.Color(240, 255, 255));
        chk_costo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        chk_costo.setText("COSTO");
        chk_costo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_costoActionPerformed(evt);
            }
        });
        jPanel2.add(chk_costo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        chk_centrocosto.setBackground(new java.awt.Color(240, 255, 255));
        chk_centrocosto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        chk_centrocosto.setText("CENTRO COSTO");
        chk_centrocosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_centrocostoActionPerformed(evt);
            }
        });
        jPanel2.add(chk_centrocosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        cmb_centrocosto.setBackground(new java.awt.Color(240, 255, 255));
        cmb_centrocosto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmb_centrocosto.setEnabled(false);
        jPanel2.add(cmb_centrocosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 350, 30));

        chk_equipo.setBackground(new java.awt.Color(240, 255, 255));
        chk_equipo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        chk_equipo.setText("EQUIPO");
        chk_equipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_equipoActionPerformed(evt);
            }
        });
        jPanel2.add(chk_equipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        cmb_equipo.setBackground(new java.awt.Color(240, 255, 255));
        cmb_equipo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmb_equipo.setEnabled(false);
        jPanel2.add(cmb_equipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 230, 30));

        cmb_costo.setBackground(new java.awt.Color(240, 255, 255));
        cmb_costo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmb_costo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "REPUESTOS", "MATERIALES", "CONSUMIBLES", "PKF" }));
        cmb_costo.setEnabled(false);
        jPanel2.add(cmb_costo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 230, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 630, 190));

        bot_excel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bot_excel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/excel.png"))); // NOI18N
        bot_excel.setText(" GENERAR DATA EN EXCEL");
        bot_excel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_excelActionPerformed(evt);
            }
        });
        getContentPane().add(bot_excel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 650, -1, -1));

        bot_limpiar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bot_limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eraser.png"))); // NOI18N
        bot_limpiar.setText("REINICIAR");
        bot_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_limpiarActionPerformed(evt);
            }
        });
        getContentPane().add(bot_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 650, -1, -1));

        bot_cerrar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bot_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/close.png"))); // NOI18N
        bot_cerrar.setText("CERRAR");
        bot_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_cerrarActionPerformed(evt);
            }
        });
        getContentPane().add(bot_cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 650, -1, -1));

        lbl_informe.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbl_informe.setForeground(new java.awt.Color(0, 0, 255));
        lbl_informe.setText("MODULO DATA DE COSTOS DE STOCK");
        getContentPane().add(lbl_informe, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        grupo_informe.add(radio_detallado);
        radio_detallado.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        radio_detallado.setSelected(true);
        radio_detallado.setText("DETALLADO");
        getContentPane().add(radio_detallado, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, -1, -1));

        grupo_informe.add(radio_resumen);
        radio_resumen.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        radio_resumen.setText("RESUMEN");
        getContentPane().add(radio_resumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 330, -1, -1));

        jPanel3.setBackground(new java.awt.Color(240, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 630, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bot_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_cerrarActionPerformed
       this.dispose();
    }//GEN-LAST:event_bot_cerrarActionPerformed

    private void bot_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_limpiarActionPerformed
        frm_reporte frm = new frm_reporte();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bot_limpiarActionPerformed

    private void cmb_mesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_mesActionPerformed
       String sql;
        
       if(evt.getModifiers() != 0){
            sql = "SELECT DISTINCT YEAR(fecha_llegada) AS ano, 'Cadena' as Cadena "; 
            sql += "FROM tbl_entrada "; 
            sql += "WHERE MONTH(fecha_llegada) = " + funciones.descripcion_mes_num(cmb_mes.getSelectedItem().toString());
            sql += " ORDER BY YEAR(fecha_llegada) DESC;";
        
            cmb_ano = funciones.cargar_combo(cmb_ano,sql,"Seleccione...");
       }   
       
    }//GEN-LAST:event_cmb_mesActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       String sql;
        
        sql="SELECT DISTINCT MONTH(fecha_llegada) AS mes FROM tbl_entrada ORDER BY MONTH(fecha_llegada);"; 
        cmb_mes = funciones.cargar_combo_mes(cmb_mes,sql,"Seleccione...");

        sql="SELECT id_equipo,equipo FROM tbl_equipo;"; 
        cmb_equipo = funciones.cargar_combo(cmb_equipo,sql,"Seleccione...");
        
        sql="SELECT id_centrocosto,centrocosto FROM tbl_centrocosto;"; 
        cmb_centrocosto = funciones.cargar_combo(cmb_centrocosto,sql,"Seleccione...");


        
    }//GEN-LAST:event_formWindowOpened

    private void radio_anoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_anoActionPerformed
       
        String sql;

        cmb_mes.setEnabled(false);
        cmb_ano.setEnabled(false);
        cmb_anual.setEnabled(true);
        date_desde.setEnabled(false);
        date_hasta.setEnabled(false);
        date_desde.setDate(null);
        date_hasta.setDate(null);
        cmb_mes.setSelectedItem("Seleccione...");
        cmb_ano.setSelectedItem("Seleccione...");

        
        sql="SELECT DISTINCT YEAR(fecha_llegada) AS ano,'Cadena' as Cadena FROM tbl_entrada ORDER BY YEAR(fecha_llegada);"; 
        cmb_anual = funciones.cargar_combo(cmb_anual,sql,"Seleccione...");
    }//GEN-LAST:event_radio_anoActionPerformed

    private void radio_rangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_rangoActionPerformed
        cmb_mes.setEnabled(false);
        cmb_ano.setEnabled(false);
        cmb_anual.setEnabled(false);
        date_desde.setEnabled(true);
        date_hasta.setEnabled(true);
        date_desde.setDate(null);
        date_hasta.setDate(null);
        cmb_mes.setSelectedItem("Seleccione...");
        cmb_ano.setSelectedItem("Seleccione...");
        cmb_anual.setSelectedItem("Seleccione...");

    }//GEN-LAST:event_radio_rangoActionPerformed

    private void radio_mesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_mesActionPerformed
        cmb_mes.setEnabled(true);
        cmb_ano.setEnabled(true);
        cmb_anual.setEnabled(false);
        date_desde.setEnabled(false);
        date_hasta.setEnabled(false);
        date_desde.setDate(null);
        date_hasta.setDate(null);
        cmb_mes.setSelectedItem("Seleccione...");
        cmb_ano.setSelectedItem("Seleccione...");
        cmb_anual.setSelectedItem("Seleccione..."); 

    }//GEN-LAST:event_radio_mesActionPerformed

    private void chk_costoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_costoActionPerformed
        if (chk_costo.isSelected()){
            cmb_costo.setEnabled(true);
        }
        else{
            cmb_costo.setEnabled(false);
        }
    }//GEN-LAST:event_chk_costoActionPerformed

    private void chk_centrocostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_centrocostoActionPerformed
        if (chk_centrocosto.isSelected()){
            cmb_centrocosto.setEnabled(true);
        }
        else{
            cmb_centrocosto.setEnabled(false);
        }
    }//GEN-LAST:event_chk_centrocostoActionPerformed

    private void chk_equipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_equipoActionPerformed
        if (chk_equipo.isSelected()){
            cmb_equipo.setEnabled(true);
        }
        else{
            cmb_equipo.setEnabled(false);
        }
    }//GEN-LAST:event_chk_equipoActionPerformed

    private void bot_excelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_excelActionPerformed
        String fecha_desde=null;
        String fecha_hasta=null; 
        String costo = null;
        Integer mes = -1;
        Integer ano = -1;
        Integer centrocosto = -1;
        Integer equipo = -1;
        boolean opcion = false;
        
        String nombre_archivo;
        
        if (radio_detallado.isSelected()){
        
            nombre_archivo = "C:/Documentos_Sistock/DataReporteDetallado.xls";
       
        }    
        else{
                
            nombre_archivo = "C:/Documentos_Sistock/DataReporteResumen.xls";
                
        }    
        
        if(radio_rango.isSelected()){
            fecha_desde = funciones.fecha_convertir_date(date_desde,1);
            fecha_hasta = funciones.fecha_convertir_date(date_hasta,1);
            if (!fecha_desde.equals("") && !fecha_hasta.equals("")){
                opcion = true;
            }
        }
        
        if(radio_mes.isSelected()){
            mes = funciones.descripcion_mes_num(cmb_mes.getSelectedItem().toString());
            ano = Integer.parseInt(cmb_ano.getSelectedItem().toString()); 
            opcion = true;
        }
        
        if(radio_ano.isSelected()){
            ano = Integer.parseInt(cmb_anual.getSelectedItem().toString());  
            opcion = true;
        }
        
        if(chk_costo.isSelected()){
            costo = cmb_costo.getSelectedItem().toString();
            opcion = true;
        }
        
        if(chk_centrocosto.isSelected()){
            centrocosto = Integer.parseInt(cmb_centrocosto.getSelectedItem().toString().substring(0,6).trim());
            opcion = true;
        }
        
        if(chk_equipo.isSelected()){
            equipo = Integer.parseInt(cmb_equipo.getSelectedItem().toString().substring(0,3).trim());
            opcion = true;
        }
        
        if (opcion){
        
            stock st = new stock(fecha_desde,fecha_hasta,mes,ano,costo,centrocosto,equipo);
        
            st.datastockimp_nac_pkf(tabla_resumen);
        
            if (radio_detallado.isSelected()){
        
                if (tabla_resumen.getRowCount() > 0){
                
                    reporte_excel ex = new reporte_excel(new File(nombre_archivo), "DATOS DE REP,CONS, MAT,PKF", tabla_resumen);
        
                    try {
                        if(ex.excel_export_reporte()){
                
                            File archivo_abrir = new File(nombre_archivo);
                            Desktop.getDesktop().open(archivo_abrir);
                
                        }
                        else{
                            JOptionPane.showMessageDialog(null, "ERROR EN EXPORTAR ARCHIVO EXCEL");
                        }
                    } catch (IOException | WriteException ex1) {
                    JOptionPane.showMessageDialog(null, "ERROR ABRIR ARCHIVO");
                }

            }
            else{
                JOptionPane.showMessageDialog(null, "SIN REGISTROS EN LA BASE DE DATOS CON LA OPCION SELECCIONDA");
            }
         
        }
        else{
            if (tabla_resumen.getRowCount() > 0){
                
                reporte_excel ex = new reporte_excel(new File(nombre_archivo), "DATOS DE REP,CONS, MAT,PKF", tabla_resumen);
        
        
                try {
                    if(ex.excel_repote_resumen_area()){
                
                        File archivo_abrir = new File(nombre_archivo);
                        Desktop.getDesktop().open(archivo_abrir);
                
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "ERROR EN EXPORTAR ARCHIVO EXCEL");
                    }
                } catch (IOException | WriteException ex1) {
                    JOptionPane.showMessageDialog(null, "ERROR ABRIR ARCHIVO");
                }

            }
            else{
                JOptionPane.showMessageDialog(null, "SIN REGISTROS EN LA BASE DE DATOS CON LA OPCION SELECCIONDA");
            }
        }
      
      }
      else{
           JOptionPane.showMessageDialog(null, "DEBE SELECCIONAR UNA OPCION PARA GENERAR EL INFORME");            
      }  
        
    }//GEN-LAST:event_bot_excelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_reporte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bot_cerrar;
    private javax.swing.JButton bot_excel;
    private javax.swing.JButton bot_limpiar;
    private javax.swing.JCheckBox chk_centrocosto;
    private javax.swing.JCheckBox chk_costo;
    private javax.swing.JCheckBox chk_equipo;
    private javax.swing.JComboBox<String> cmb_ano;
    private javax.swing.JComboBox<String> cmb_anual;
    private javax.swing.JComboBox<String> cmb_centrocosto;
    private javax.swing.JComboBox<String> cmb_costo;
    private javax.swing.JComboBox<String> cmb_equipo;
    private javax.swing.JComboBox<String> cmb_mes;
    private com.toedter.calendar.JDateChooser date_desde;
    private com.toedter.calendar.JDateChooser date_hasta;
    private javax.swing.ButtonGroup grupo_fecha;
    private javax.swing.ButtonGroup grupo_informe;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_informe;
    private javax.swing.JRadioButton radio_ano;
    private javax.swing.JRadioButton radio_detallado;
    private javax.swing.JRadioButton radio_mes;
    private javax.swing.JRadioButton radio_rango;
    private javax.swing.JRadioButton radio_resumen;
    private javax.swing.JTable tabla_resumen;
    // End of variables declaration//GEN-END:variables
}
