/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistock;

import java.awt.Color;
import static java.awt.Frame.MAXIMIZED_BOTH;
import javax.swing.JOptionPane;

/**
 *
 * @author ruben
 */
public class frm_centrocosto extends javax.swing.JFrame {

    /**
     * Creates new form frm_centrocosto
     */
    public frm_centrocosto() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("SISTOCK - CENTRO COSTO");
        this.getContentPane().setBackground(Color.WHITE);
        this.setExtendedState(MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_encabezadocc = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_centrocosto = new javax.swing.JTable();
        bot_cerrar = new javax.swing.JButton();
        bot_limpiar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        radio_crearcentrocosto = new javax.swing.JRadioButton();
        lbl_centrocosto = new javax.swing.JLabel();
        txt_idcentrocosto = new javax.swing.JTextField();
        lbl_descentrocosto = new javax.swing.JLabel();
        txt_centrocosto = new javax.swing.JTextField();
        bot_crear = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        radio_actualizarcentrocosto = new javax.swing.JRadioButton();
        lbl_desnuevocc = new javax.swing.JLabel();
        lbl_nuevacentrocosto = new javax.swing.JLabel();
        lbl_nuevoidcentrocosto = new javax.swing.JLabel();
        txt_nuevoidcentrocosto = new javax.swing.JTextField();
        txt_nuevacentrocosto = new javax.swing.JTextField();
        cmb_centrocosto = new javax.swing.JComboBox();
        bot_actualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_encabezadocc.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbl_encabezadocc.setForeground(new java.awt.Color(0, 0, 255));
        lbl_encabezadocc.setText("MÓDULO DE CENTRO DE COSTO");
        getContentPane().add(lbl_encabezadocc, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, -1, -1));

        table_centrocosto.setBackground(new java.awt.Color(240, 255, 255));
        table_centrocosto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        table_centrocosto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "DESCRIPCION"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(table_centrocosto);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, 720, 160));

        bot_cerrar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bot_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/close.png"))); // NOI18N
        bot_cerrar.setText("CERRAR");
        bot_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_cerrarActionPerformed(evt);
            }
        });
        getContentPane().add(bot_cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 630, -1, -1));

        bot_limpiar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bot_limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eraser.png"))); // NOI18N
        bot_limpiar.setText("REINICIAR");
        bot_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_limpiarActionPerformed(evt);
            }
        });
        getContentPane().add(bot_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 630, -1, -1));

        jPanel1.setBackground(new java.awt.Color(240, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        radio_crearcentrocosto.setBackground(new java.awt.Color(240, 255, 255));
        radio_crearcentrocosto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        radio_crearcentrocosto.setSelected(true);
        radio_crearcentrocosto.setText("CREAR CENTRO DE COSTO");
        radio_crearcentrocosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_crearcentrocostoActionPerformed(evt);
            }
        });
        jPanel1.add(radio_crearcentrocosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lbl_centrocosto.setBackground(new java.awt.Color(240, 255, 255));
        lbl_centrocosto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_centrocosto.setText("ID CENTRO COSTO");
        jPanel1.add(lbl_centrocosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 20));

        txt_idcentrocosto.setBackground(new java.awt.Color(240, 255, 255));
        txt_idcentrocosto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txt_idcentrocosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 160, -1));

        lbl_descentrocosto.setBackground(new java.awt.Color(240, 255, 255));
        lbl_descentrocosto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_descentrocosto.setText("DESCRIPCIÓN CENTRO COSTO");
        jPanel1.add(lbl_descentrocosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        txt_centrocosto.setBackground(new java.awt.Color(240, 255, 255));
        txt_centrocosto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_centrocosto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_centrocostoKeyPressed(evt);
            }
        });
        jPanel1.add(txt_centrocosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 300, -1));

        bot_crear.setBackground(new java.awt.Color(240, 255, 255));
        bot_crear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bot_crear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/databasesave.png"))); // NOI18N
        bot_crear.setText("CREAR");
        bot_crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_crearActionPerformed(evt);
            }
        });
        jPanel1.add(bot_crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 70, 170, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 820, 130));

        jPanel2.setBackground(new java.awt.Color(240, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        radio_actualizarcentrocosto.setBackground(new java.awt.Color(240, 255, 255));
        radio_actualizarcentrocosto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        radio_actualizarcentrocosto.setText("ACTUALIZAR CENTRO DE COSTO");
        radio_actualizarcentrocosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_actualizarcentrocostoActionPerformed(evt);
            }
        });
        jPanel2.add(radio_actualizarcentrocosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        lbl_desnuevocc.setBackground(new java.awt.Color(240, 255, 255));
        lbl_desnuevocc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_desnuevocc.setText("CENTRO DE COSTO");
        jPanel2.add(lbl_desnuevocc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        lbl_nuevacentrocosto.setBackground(new java.awt.Color(240, 255, 255));
        lbl_nuevacentrocosto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_nuevacentrocosto.setText("NUEVA DESCRIPCION C.C");
        jPanel2.add(lbl_nuevacentrocosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        lbl_nuevoidcentrocosto.setBackground(new java.awt.Color(240, 255, 255));
        lbl_nuevoidcentrocosto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_nuevoidcentrocosto.setText("NUEVO ID CENTRO COSTO");
        jPanel2.add(lbl_nuevoidcentrocosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        txt_nuevoidcentrocosto.setBackground(new java.awt.Color(240, 255, 255));
        txt_nuevoidcentrocosto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_nuevoidcentrocosto.setEnabled(false);
        jPanel2.add(txt_nuevoidcentrocosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 160, -1));

        txt_nuevacentrocosto.setBackground(new java.awt.Color(240, 255, 255));
        txt_nuevacentrocosto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_nuevacentrocosto.setEnabled(false);
        txt_nuevacentrocosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nuevacentrocostoActionPerformed(evt);
            }
        });
        txt_nuevacentrocosto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nuevacentrocostoKeyPressed(evt);
            }
        });
        jPanel2.add(txt_nuevacentrocosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 340, -1));

        cmb_centrocosto.setBackground(new java.awt.Color(240, 255, 255));
        cmb_centrocosto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmb_centrocosto.setEnabled(false);
        cmb_centrocosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_centrocostoActionPerformed(evt);
            }
        });
        jPanel2.add(cmb_centrocosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 340, -1));

        bot_actualizar.setBackground(new java.awt.Color(240, 255, 255));
        bot_actualizar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bot_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/refresh.png"))); // NOI18N
        bot_actualizar.setText("ACTUALIZAR");
        bot_actualizar.setEnabled(false);
        bot_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_actualizarActionPerformed(evt);
            }
        });
        jPanel2.add(bot_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 60, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 820, 140));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bot_crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_crearActionPerformed
        String sql;
        boolean resp;
        
        if(!txt_centrocosto.getText().equals("")) {

                centrocosto cc = new centrocosto(Integer.parseInt(txt_idcentrocosto.getText().trim()),txt_centrocosto.getText().trim().toUpperCase(),2);

                resp = cc.actualizar_centrocosto();
                
                if (resp){
                   cc.consulta_cc(table_centrocosto);
                   sql="select id_centrocosto,centrocosto from tbl_centrocosto;";       
                   cmb_centrocosto = funciones.cargar_combo(cmb_centrocosto,sql,txt_centrocosto.getText().toUpperCase().trim());
                   
                   txt_idcentrocosto.setText("");
                   txt_centrocosto.setText("");
                   
                }
                
        }
        else{
            JOptionPane.showMessageDialog(null,"DATOS INCOMPLETOS PARA GUARDAR");
        }
    }//GEN-LAST:event_bot_crearActionPerformed

    private void bot_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_cerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_bot_cerrarActionPerformed

    private void radio_crearcentrocostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_crearcentrocostoActionPerformed
        txt_centrocosto.setEnabled(true);
        bot_crear.setEnabled(true);
        cmb_centrocosto.setEnabled(false);
        txt_nuevacentrocosto.setEnabled(false);
        txt_nuevoidcentrocosto.setEnabled(false);
        bot_actualizar.setEnabled(false);
        radio_actualizarcentrocosto.setSelected(false);      
    }//GEN-LAST:event_radio_crearcentrocostoActionPerformed

    private void radio_actualizarcentrocostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_actualizarcentrocostoActionPerformed
        txt_centrocosto.setText("");
        txt_centrocosto.setEnabled(false);
        bot_crear.setEnabled(false);
        cmb_centrocosto.setEnabled(true);
        txt_nuevacentrocosto.setEnabled(true);
        txt_nuevoidcentrocosto.setEnabled(true);
        bot_actualizar.setEnabled(true);
        radio_crearcentrocosto.setSelected(false);        
    }//GEN-LAST:event_radio_actualizarcentrocostoActionPerformed

    private void bot_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_actualizarActionPerformed
        boolean resp = true;
        String sql;
         
        
        if(!txt_nuevacentrocosto.getText().equals("") && !txt_nuevoidcentrocosto.getText().equals("") && !cmb_centrocosto.getSelectedItem().equals("Seleccione...") ) {

            if (!txt_nuevoidcentrocosto.getText().equals(cmb_centrocosto.getSelectedItem().toString().substring(0,6).trim())){
                
                centrocosto cc = new centrocosto(Integer.parseInt(txt_nuevoidcentrocosto.getText().trim()),2);
                
                resp = cc.buscar_idcentrocosto();
                
            }
            
            if (resp){
                centrocosto cc = new centrocosto(Integer.parseInt(cmb_centrocosto.getSelectedItem().toString().substring(0,6).trim()),Integer.parseInt(txt_nuevoidcentrocosto.getText().trim()),txt_nuevacentrocosto.getText().trim().toUpperCase(),3);

                resp = cc.actualizar_centrocosto_detalle();

                if (resp){
                    cc.consulta_cc(table_centrocosto);
                    
                    sql="select id_centrocosto,centrocosto from tbl_centrocosto;";       
        
                    cmb_centrocosto = funciones.cargar_combo(cmb_centrocosto,sql,txt_nuevacentrocosto.getText().trim().toUpperCase());
                    
                    txt_nuevacentrocosto.setText("");
                    
                    txt_nuevoidcentrocosto.setText("");
                    
                    /*if (frm_pesaje.ventana_activa_ruta.equals(true)){
                           
                       frm_pesaje.cmb_ruta = funciones.cargar_combo(frm_pesaje.cmb_ruta,sql,txt_nuevacentrocosto.getText().trim().toUpperCase());
                        
                    }*/
                }
            }
        }
        else{

            JOptionPane.showMessageDialog(null,"DATOS INCOMPLETOS PARA ACTUALIZAR");
        }
    }//GEN-LAST:event_bot_actualizarActionPerformed

    private void bot_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_limpiarActionPerformed
        txt_centrocosto.setText("");
        bot_crear.setEnabled(true);
        cmb_centrocosto.setEnabled(false);
        txt_nuevacentrocosto.setText("");
        txt_nuevoidcentrocosto.setText("");
        bot_actualizar.setEnabled(false);
        radio_actualizarcentrocosto.setSelected(false); 
    }//GEN-LAST:event_bot_limpiarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        String sql;
        
        centrocosto cc = new centrocosto();
        cc.consulta_cc(table_centrocosto);
        
        txt_idcentrocosto.requestFocusInWindow();
        
        
        sql="select id_centrocosto,centrocosto from tbl_centrocosto;";       
        
        cmb_centrocosto = funciones.cargar_combo(cmb_centrocosto,sql,"Seleccione...");
    }//GEN-LAST:event_formWindowOpened

    private void txt_centrocostoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_centrocostoKeyPressed
        if (evt.getKeyCode()==10){
            bot_crear.doClick();
        }
        
        if (evt.getKeyCode() == 27){
         
            bot_limpiar.doClick();
                    
        }
    }//GEN-LAST:event_txt_centrocostoKeyPressed

    private void txt_nuevacentrocostoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nuevacentrocostoKeyPressed
       if (evt.getKeyCode()==10){
            bot_actualizar.doClick();
        }
        
        if (evt.getKeyCode() == 27){
         
            bot_limpiar.doClick();
                    
        }
    }//GEN-LAST:event_txt_nuevacentrocostoKeyPressed

    private void cmb_centrocostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_centrocostoActionPerformed
        //JOptionPane.showMessageDialog(this, evt.getModifiers());
        if(evt.getModifiers() != 0){
            if (cmb_centrocosto.getSelectedItem().equals("Seleccione...")){
                txt_nuevoidcentrocosto.setText(""); 
                txt_nuevacentrocosto.setText("");
            }
            else{
                txt_nuevoidcentrocosto.setText(cmb_centrocosto.getSelectedItem().toString().substring(0,6).trim());
                txt_nuevacentrocosto.setText(cmb_centrocosto.getSelectedItem().toString().substring(10,cmb_centrocosto.getSelectedItem().toString().length()).trim());
            }
        }
        
    }//GEN-LAST:event_cmb_centrocostoActionPerformed

    private void txt_nuevacentrocostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nuevacentrocostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nuevacentrocostoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_centrocosto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_centrocosto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_centrocosto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_centrocosto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_centrocosto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bot_actualizar;
    private javax.swing.JButton bot_cerrar;
    private javax.swing.JButton bot_crear;
    private javax.swing.JButton bot_limpiar;
    private javax.swing.JComboBox cmb_centrocosto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_centrocosto;
    private javax.swing.JLabel lbl_descentrocosto;
    private javax.swing.JLabel lbl_desnuevocc;
    private javax.swing.JLabel lbl_encabezadocc;
    private javax.swing.JLabel lbl_nuevacentrocosto;
    private javax.swing.JLabel lbl_nuevoidcentrocosto;
    private javax.swing.JRadioButton radio_actualizarcentrocosto;
    private javax.swing.JRadioButton radio_crearcentrocosto;
    private javax.swing.JTable table_centrocosto;
    private javax.swing.JTextField txt_centrocosto;
    private javax.swing.JTextField txt_idcentrocosto;
    private javax.swing.JTextField txt_nuevacentrocosto;
    private javax.swing.JTextField txt_nuevoidcentrocosto;
    // End of variables declaration//GEN-END:variables
}
