/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistock;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author ruben
 */
public class frm_equipo extends javax.swing.JFrame {

    /**
     * Creates new form frm_equipo
     */
    public frm_equipo() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.WHITE);
        this.setTitle("SISTOCK - EQUIPOS");
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_codigofapco = new javax.swing.JTextField();
        lbl_codfapco = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_equipo = new javax.swing.JTextField();
        lbl_marca = new javax.swing.JLabel();
        txt_marca = new javax.swing.JTextField();
        lbl_modelo = new javax.swing.JLabel();
        txt_modelo = new javax.swing.JTextField();
        lbl_ubicacion = new javax.swing.JLabel();
        txt_ubicacion = new javax.swing.JTextField();
        lbl_carroceria = new javax.swing.JLabel();
        txt_carroceria = new javax.swing.JTextField();
        lbl_area = new javax.swing.JLabel();
        lbl_estatus = new javax.swing.JLabel();
        lbl_propiedad = new javax.swing.JLabel();
        cmb_propiedad = new javax.swing.JComboBox();
        cmb_centrocosto = new javax.swing.JComboBox();
        cmb_estatus = new javax.swing.JComboBox();
        bot_guardar = new javax.swing.JButton();
        bot_actualizar = new javax.swing.JButton();
        bot_buscar = new javax.swing.JButton();
        bot_limpiar = new javax.swing.JButton();
        bot_cerrar = new javax.swing.JButton();
        lbl_encabezado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_codigofapco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txt_codigofapco, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 160, -1));

        lbl_codfapco.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_codfapco.setText("COD. FAPCO");
        getContentPane().add(lbl_codfapco, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("EQUIPO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, -1, -1));

        txt_equipo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_equipo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_equipoKeyPressed(evt);
            }
        });
        getContentPane().add(txt_equipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, 160, -1));

        lbl_marca.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_marca.setText("MARCA");
        getContentPane().add(lbl_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, -1, -1));

        txt_marca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txt_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 160, -1));

        lbl_modelo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_modelo.setText("MODELO");
        getContentPane().add(lbl_modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, -1, -1));

        txt_modelo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txt_modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, 160, -1));

        lbl_ubicacion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_ubicacion.setText("UBICACIÓN");
        getContentPane().add(lbl_ubicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, -1, -1));

        txt_ubicacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txt_ubicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, 160, -1));

        lbl_carroceria.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_carroceria.setText("SERIAL CARROCERÍA");
        getContentPane().add(lbl_carroceria, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, -1, -1));

        txt_carroceria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_carroceria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_carroceriaActionPerformed(evt);
            }
        });
        getContentPane().add(txt_carroceria, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, 300, -1));

        lbl_area.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_area.setText("ÁREA");
        getContentPane().add(lbl_area, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 440, -1, -1));

        lbl_estatus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_estatus.setText("ESTATUS");
        getContentPane().add(lbl_estatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 500, -1, -1));

        lbl_propiedad.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_propiedad.setText("PROPIEDAD");
        getContentPane().add(lbl_propiedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 560, -1, -1));

        cmb_propiedad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(cmb_propiedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 560, 300, -1));

        cmb_centrocosto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmb_centrocosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_centrocostoActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_centrocosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 440, 300, -1));

        cmb_estatus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(cmb_estatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 500, 300, -1));

        bot_guardar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bot_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/databasesave.png"))); // NOI18N
        bot_guardar.setText("GUARDAR");
        bot_guardar.setEnabled(false);
        bot_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_guardarActionPerformed(evt);
            }
        });
        getContentPane().add(bot_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 630, -1, -1));

        bot_actualizar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bot_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/refresh.png"))); // NOI18N
        bot_actualizar.setText("ACTUALIZAR");
        bot_actualizar.setEnabled(false);
        bot_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_actualizarActionPerformed(evt);
            }
        });
        getContentPane().add(bot_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 630, -1, -1));

        bot_buscar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bot_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Search.png"))); // NOI18N
        bot_buscar.setText("BUSCAR");
        bot_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_buscarActionPerformed(evt);
            }
        });
        getContentPane().add(bot_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 80, -1, -1));

        bot_limpiar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bot_limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eraser.png"))); // NOI18N
        bot_limpiar.setText("REINICIAR");
        bot_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_limpiarActionPerformed(evt);
            }
        });
        getContentPane().add(bot_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 630, -1, -1));

        bot_cerrar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bot_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/close.png"))); // NOI18N
        bot_cerrar.setText("CERRAR");
        bot_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_cerrarActionPerformed(evt);
            }
        });
        getContentPane().add(bot_cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 630, -1, -1));

        lbl_encabezado.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbl_encabezado.setForeground(new java.awt.Color(0, 0, 255));
        lbl_encabezado.setText("MÓDULO EQUIPOS");
        getContentPane().add(lbl_encabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bot_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_guardarActionPerformed
        
        Boolean resp;
        
        if (!txt_equipo.getText().equals("") &&
            !txt_codigofapco.getText().equals("") &&
            !txt_marca.getText().equals("") &&
            !txt_modelo.getText().equals("") &&
            !txt_ubicacion.getText().equals("") &&
            !txt_carroceria.getText().equals("") &&
            !cmb_centrocosto.getSelectedItem().equals("Seleccione...") &&    
            !cmb_estatus.getSelectedItem().equals("Seleccione...") && 
            !cmb_propiedad.getSelectedItem().equals("Seleccione...") ){
            
            equipo eq = new equipo(txt_equipo.getText().trim().toUpperCase(),
                                    txt_codigofapco.getText().trim().toUpperCase(),
                                    txt_marca.getText().trim().toUpperCase(),
                                    txt_modelo.getText().trim().toUpperCase(),
                                    txt_ubicacion.getText().trim().toUpperCase(),    
                                    txt_carroceria.getText().trim().toUpperCase(),
                                    Integer.parseInt(cmb_centrocosto.getSelectedItem().toString().substring(0, 6).trim()),
                                    Integer.parseInt(cmb_estatus.getSelectedItem().toString().trim().substring(0, 3).trim()),
                                    Integer.parseInt(cmb_propiedad.getSelectedItem().toString().trim().substring(0, 3).trim()),2 );
            
            
            
             resp = eq.actualizar_equipo();
            
             if (resp){
                    bot_guardar.setEnabled(false);
                    bot_actualizar.setEnabled(true);
                    bot_limpiar.setEnabled(true);
             }
        }
        else{
            JOptionPane.showMessageDialog(null,"DATOS INCOMPLETOS PARA GUARDAR");
        }
        
        
        
        
    }//GEN-LAST:event_bot_guardarActionPerformed

    private void bot_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_actualizarActionPerformed
        Boolean resp;
        
        if (!txt_equipo.getText().equals("") &&
            !txt_codigofapco.getText().equals("") &&
            !txt_marca.getText().equals("") &&
            !txt_modelo.getText().equals("") &&
            !txt_ubicacion.getText().equals("") &&
            !txt_carroceria.getText().equals("") &&
            !cmb_centrocosto.getSelectedItem().equals("Seleccione...") &&    
            !cmb_estatus.getSelectedItem().equals("Seleccione...") && 
            !cmb_propiedad.getSelectedItem().equals("Seleccione...") ){
            
            equipo eq = new equipo(txt_equipo.getText().trim().toUpperCase(),
                                    txt_codigofapco.getText().trim().toUpperCase(),
                                    txt_marca.getText().trim().toUpperCase(),
                                    txt_modelo.getText().trim().toUpperCase(),
                                    txt_ubicacion.getText().trim().toUpperCase(),    
                                    txt_carroceria.getText().trim().toUpperCase(),
                                    Integer.parseInt(cmb_centrocosto.getSelectedItem().toString().substring(0, 6).trim()),
                                    Integer.parseInt(cmb_estatus.getSelectedItem().toString().trim().substring(0, 3).trim()),
                                    Integer.parseInt(cmb_propiedad.getSelectedItem().toString().trim().substring(0, 3).trim()),3);
            
            
            
             resp = eq.actualizar_equipo_detalle();
            
             
        }
        else{
            JOptionPane.showMessageDialog(null,"DATOS INCOMPLETOS PARA ACTUALIZAR");
        }
    }//GEN-LAST:event_bot_actualizarActionPerformed

    private void bot_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_cerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_bot_cerrarActionPerformed

    private void bot_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_buscarActionPerformed
       boolean resp;
       String tmp;
       String sql;
        
        
        if (!txt_equipo.getText().equals("")){

            equipo eq = new equipo(txt_equipo.getText().trim().toUpperCase(),4);

            resp = eq.buscar_equipo();

            if (resp){

                txt_equipo.setText(eq.getEquipo());
                txt_codigofapco.setText(eq.getCodigofapco());
                txt_marca.setText(eq.getMarca()) ;
                txt_modelo.setText(eq.getModelo());
                txt_ubicacion.setText(eq.getUbicacion());
                txt_carroceria.setText(eq.getCarroceria());
                sql="SELECT id_centrocosto,centrocosto FROM tbl_centrocosto;"; 
                cmb_centrocosto = funciones.cargar_combo(cmb_centrocosto,sql,eq.getDescripcion_centrocosto());
                sql="SELECT id_estatus,descripcion FROM tbl_estatus;"; 
                cmb_estatus = funciones.cargar_combo(cmb_estatus,sql,eq.getDescripcion_estatus());
                sql="SELECT id_propiedad,descripcion FROM tbl_propiedad;"; 
                cmb_propiedad = funciones.cargar_combo(cmb_propiedad,sql,eq.getDescripcion_propiedad());
                    
                
                bot_actualizar.setEnabled(true);
                bot_guardar.setEnabled(false);
                bot_limpiar.setEnabled(true);
                    
                
                
            }
            else{
                bot_actualizar.setEnabled(false); 
                bot_limpiar.setEnabled(true);
                bot_guardar.setEnabled(true);
                txt_codigofapco.requestFocusInWindow();
                
            }

        }
        else{
            JOptionPane.showMessageDialog(null,"FAVOR INTRODUCIR NOMBRE DEL EQUIPO");
        }
    }//GEN-LAST:event_bot_buscarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        String sql;
        
        sql="SELECT id_centrocosto,centrocosto FROM tbl_centrocosto;"; 
        cmb_centrocosto = funciones.cargar_combo(cmb_centrocosto,sql,"Seleccione...");
        sql="SELECT id_estatus,descripcion FROM tbl_estatus;"; 
        cmb_estatus = funciones.cargar_combo(cmb_estatus,sql,"Seleccione...");
        sql="SELECT id_propiedad,descripcion FROM tbl_propiedad;"; 
        cmb_propiedad = funciones.cargar_combo(cmb_propiedad,sql,"Seleccione...");
       
        txt_equipo.requestFocusInWindow();
        
    }//GEN-LAST:event_formWindowOpened

    private void bot_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_limpiarActionPerformed
        frm_equipo frm = new frm_equipo();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bot_limpiarActionPerformed

    private void txt_equipoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_equipoKeyPressed
        if (evt.getKeyCode()==10){
            bot_buscar.doClick();
        }
        
        if (evt.getKeyCode() == 27){
         
            bot_limpiar.doClick();
                    
        }
    }//GEN-LAST:event_txt_equipoKeyPressed

    private void cmb_centrocostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_centrocostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_centrocostoActionPerformed

    private void txt_carroceriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_carroceriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_carroceriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_equipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_equipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_equipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_equipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_equipo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bot_actualizar;
    protected javax.swing.JButton bot_buscar;
    private javax.swing.JButton bot_cerrar;
    private javax.swing.JButton bot_guardar;
    private javax.swing.JButton bot_limpiar;
    private javax.swing.JComboBox cmb_centrocosto;
    private javax.swing.JComboBox cmb_estatus;
    private javax.swing.JComboBox cmb_propiedad;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbl_area;
    private javax.swing.JLabel lbl_carroceria;
    private javax.swing.JLabel lbl_codfapco;
    private javax.swing.JLabel lbl_encabezado;
    private javax.swing.JLabel lbl_estatus;
    private javax.swing.JLabel lbl_marca;
    private javax.swing.JLabel lbl_modelo;
    private javax.swing.JLabel lbl_propiedad;
    private javax.swing.JLabel lbl_ubicacion;
    private javax.swing.JTextField txt_carroceria;
    private javax.swing.JTextField txt_codigofapco;
    protected javax.swing.JTextField txt_equipo;
    private javax.swing.JTextField txt_marca;
    private javax.swing.JTextField txt_modelo;
    private javax.swing.JTextField txt_ubicacion;
    // End of variables declaration//GEN-END:variables
}
