/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistock;

import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import jxl.write.WriteException;

/**
 *
 * @author ruben
 */
public class frm_verstockimp extends javax.swing.JFrame {

    /**
     * Creates new form frm_verstockimp
     */
    public frm_verstockimp() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.WHITE);
        this.setTitle("SISTOCK - CONSULTAR STOCK");
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        tabla_stockreporte = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabla_resumen = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_usado = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_stock = new javax.swing.JTable();
        bot_exportarexcel = new javax.swing.JButton();
        bot_limpiar = new javax.swing.JButton();
        bot_cerrar = new javax.swing.JButton();
        lbl_stock = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        check_fecha = new javax.swing.JCheckBox();
        date_desde = new com.toedter.calendar.JDateChooser();
        check_codsap = new javax.swing.JCheckBox();
        txt_codigosap = new javax.swing.JTextField();
        check_descripcion = new javax.swing.JCheckBox();
        txt_descripcion = new javax.swing.JTextField();
        check_area = new javax.swing.JCheckBox();
        cmb_centrocosto = new javax.swing.JComboBox<>();
        lbl_desde = new javax.swing.JLabel();
        lbl_hasta = new javax.swing.JLabel();
        date_hasta = new com.toedter.calendar.JDateChooser();
        cmb_equipo = new javax.swing.JComboBox<>();
        chk_equipo = new javax.swing.JCheckBox();
        bot_buscar = new javax.swing.JButton();

        tabla_stockreporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "cod", "sap", "id_centrocosto", "centrocosto", "id_equipo", "equipo", "descripcion", "fecha", "cantrecib", "cantdisp", "cantidadsalida", "preciounitario", "subtotal", "flete", "montototal", "estatus"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tabla_stockreporte);

        tabla_resumen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "sap", "descripcion", "costo", "cant_ume", "ume", "valor", "tasa_mes", "fecha", "id_equipo", "equipo", "cantrecib", "cantdisp", "cantidadsalida", "precio_unitario", "subtotal", "flete", "montototal", "estatus", "id_centrocosto", "centrocosto", "fleteNacAct", "fleteAct", "MontoTotalAct $", "fletebs"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tabla_resumen);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("STOCK");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("USADO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));

        table_usado.setBackground(new java.awt.Color(240, 255, 255));
        table_usado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        table_usado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "AREA", "EQUIPO", "CODIGO SAP", "DESCRIPCION", "FECHA SALIDA", "CANTIDAD USADA", "PRECIO UNITARIO $", "ITEM $", "FLETE $", "MONTO $", "FLETE NAC $", "TOTAL FLETE $", "MONTO TOTAL $", "fletebs"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_usado);
        if (table_usado.getColumnModel().getColumnCount() > 0) {
            table_usado.getColumnModel().getColumn(13).setMinWidth(0);
            table_usado.getColumnModel().getColumn(13).setPreferredWidth(0);
            table_usado.getColumnModel().getColumn(13).setMaxWidth(0);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 1270, 140));

        table_stock.setBackground(new java.awt.Color(240, 255, 255));
        table_stock.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        table_stock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "AREA", "CODIGO SAP", "DESCRIPCION", "FECHA LLEGADA", "CANTIDAD RECIB", "CANTIDAD DISP", "PRECIO UNITARIO $", "ITEM $", "FLETE ITEM $", "MONTO $", "FLETE NAC $", "TOTAL FLETE $", "MONTO TOTAL $", "fletebs"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(table_stock);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 1270, 110));

        bot_exportarexcel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bot_exportarexcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/excel.png"))); // NOI18N
        bot_exportarexcel.setText("EXPORTAR A EXCEL");
        bot_exportarexcel.setEnabled(false);
        bot_exportarexcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_exportarexcelActionPerformed(evt);
            }
        });
        getContentPane().add(bot_exportarexcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 630, -1, -1));

        bot_limpiar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bot_limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eraser.png"))); // NOI18N
        bot_limpiar.setText("REINICIAR");
        bot_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_limpiarActionPerformed(evt);
            }
        });
        getContentPane().add(bot_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 630, -1, -1));

        bot_cerrar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bot_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/close.png"))); // NOI18N
        bot_cerrar.setText("CERRAR");
        bot_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_cerrarActionPerformed(evt);
            }
        });
        getContentPane().add(bot_cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 630, -1, -1));

        lbl_stock.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbl_stock.setForeground(new java.awt.Color(0, 0, 255));
        lbl_stock.setText("CONSULTAR STOCK REPUESTOS");
        getContentPane().add(lbl_stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(240, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        check_fecha.setBackground(new java.awt.Color(240, 255, 255));
        check_fecha.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        check_fecha.setText("FECHA");
        check_fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_fechaActionPerformed(evt);
            }
        });
        jPanel1.add(check_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        date_desde.setBackground(new java.awt.Color(240, 255, 255));
        date_desde.setDateFormatString("dd/MM/yyyy");
        date_desde.setEnabled(false);
        date_desde.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(date_desde, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 150, 30));

        check_codsap.setBackground(new java.awt.Color(240, 255, 255));
        check_codsap.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        check_codsap.setText("CODIGO SAP");
        check_codsap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_codsapActionPerformed(evt);
            }
        });
        jPanel1.add(check_codsap, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        txt_codigosap.setBackground(new java.awt.Color(240, 255, 255));
        txt_codigosap.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_codigosap.setEnabled(false);
        txt_codigosap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_codigosapActionPerformed(evt);
            }
        });
        txt_codigosap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_codigosapKeyPressed(evt);
            }
        });
        jPanel1.add(txt_codigosap, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 130, 30));

        check_descripcion.setBackground(new java.awt.Color(240, 255, 255));
        check_descripcion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        check_descripcion.setText("DESCRIPCION");
        check_descripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_descripcionActionPerformed(evt);
            }
        });
        jPanel1.add(check_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        txt_descripcion.setBackground(new java.awt.Color(240, 255, 255));
        txt_descripcion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_descripcion.setEnabled(false);
        jPanel1.add(txt_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 280, 30));

        check_area.setBackground(new java.awt.Color(240, 255, 255));
        check_area.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        check_area.setText("CENTRO DE COSTO");
        check_area.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_areaActionPerformed(evt);
            }
        });
        jPanel1.add(check_area, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        cmb_centrocosto.setBackground(new java.awt.Color(240, 255, 255));
        cmb_centrocosto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmb_centrocosto.setEnabled(false);
        cmb_centrocosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_centrocostoActionPerformed(evt);
            }
        });
        jPanel1.add(cmb_centrocosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 360, 30));

        lbl_desde.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_desde.setForeground(new java.awt.Color(0, 0, 255));
        lbl_desde.setText("Desde");
        jPanel1.add(lbl_desde, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        lbl_hasta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_hasta.setForeground(new java.awt.Color(0, 0, 255));
        lbl_hasta.setText("Hasta");
        jPanel1.add(lbl_hasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, -1, -1));

        date_hasta.setBackground(new java.awt.Color(240, 255, 255));
        date_hasta.setDateFormatString("dd/MM/yyyy");
        date_hasta.setEnabled(false);
        date_hasta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(date_hasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 150, 30));

        cmb_equipo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmb_equipo.setEnabled(false);
        jPanel1.add(cmb_equipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 280, 30));

        chk_equipo.setBackground(new java.awt.Color(240, 255, 255));
        chk_equipo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        chk_equipo.setText("EQUIPO");
        chk_equipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_equipoActionPerformed(evt);
            }
        });
        jPanel1.add(chk_equipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 640, 280));

        bot_buscar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bot_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Search.png"))); // NOI18N
        bot_buscar.setText("BUSCAR");
        bot_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_buscarActionPerformed(evt);
            }
        });
        getContentPane().add(bot_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 180, 160, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_codigosapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_codigosapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codigosapActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        String sql;
        
        sql="SELECT id_centrocosto,centrocosto FROM tbl_centrocosto;"; 
       cmb_centrocosto = funciones.cargar_combo(cmb_centrocosto,sql,"Seleccione...");
    }//GEN-LAST:event_formWindowOpened

    private void bot_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_limpiarActionPerformed
       frm_verstockimp frm = new frm_verstockimp();
       frm.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_bot_limpiarActionPerformed

    private void bot_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_cerrarActionPerformed
        this.dispose();
        
    }//GEN-LAST:event_bot_cerrarActionPerformed

    private void check_fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_fechaActionPerformed
        
        if (check_fecha.isSelected()){
            date_desde.setEnabled(true);
            date_hasta.setEnabled(true);
        }
        else{
            date_desde.setDate(null);
            date_hasta.setDate(null);
            date_desde.setEnabled(false);
            date_hasta.setEnabled(false);
        }
        
        
    }//GEN-LAST:event_check_fechaActionPerformed

    private void check_codsapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_codsapActionPerformed
        
        if (check_codsap.isSelected()){
            txt_codigosap.setEnabled(true);
            txt_codigosap.setText("");
        }
        else{
             txt_codigosap.setText(""); 
            txt_codigosap.setEnabled(false);         
        }
    }//GEN-LAST:event_check_codsapActionPerformed

    private void check_areaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_areaActionPerformed
         if (check_area.isSelected()){
            cmb_centrocosto.setEnabled(true);
        }
        else{
            cmb_centrocosto.setEnabled(false);         
        }
    }//GEN-LAST:event_check_areaActionPerformed

    private void bot_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_buscarActionPerformed
       
       String sql;
       Integer centrocosto=0;
       Integer equipo = 0;
       boolean opcion = false;
       String fechadesde="";
       String fechahasta="";
       
       if (txt_codigosap.getText().trim().equals("")){
           txt_codigosap.setText("-1");
       }
       else{
           opcion = true;
       }
       
       if (!cmb_centrocosto.getSelectedItem().equals("Seleccione...")){
           centrocosto = Integer.parseInt(cmb_centrocosto.getSelectedItem().toString().substring(0,6));
           opcion = true;
       }
       else{
           centrocosto = -1;
       }
       
       try{
            if (!cmb_equipo.getSelectedItem().equals("Seleccione...")){
                equipo = Integer.parseInt(cmb_centrocosto.getSelectedItem().toString().substring(0,3));
                opcion = true;
            }
            else{
                equipo = -1;
            }
       }
       catch(NullPointerException ex){
          equipo = -1;
       }
       
       if (check_fecha.isSelected()){
           fechadesde = funciones.fecha_convertir_date(date_desde, 1);
           fechahasta = funciones.fecha_convertir_date(date_hasta, 1);
           
           if (!fechadesde.equals("") && !fechahasta.equals("")){
               opcion = true;
           }
       }
       
       
       if (opcion){
            stock st = new stock(fechadesde,fechahasta,Integer.parseInt(txt_codigosap.getText()),txt_descripcion.getText(),centrocosto,equipo,table_stock,table_usado);
       
            if(st.buscarstockentradasalida(true)){
                bot_exportarexcel.setEnabled(true);
                st.datastockreporte(tabla_resumen);
            }
       }
       else{
           JOptionPane.showMessageDialog(null, "DEBE SELECCIONAR UNA OPCION PARA GENERAR LA CONSULTA");
       }
    }//GEN-LAST:event_bot_buscarActionPerformed

    private void check_descripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_descripcionActionPerformed
        if (check_descripcion.isSelected()){
            txt_descripcion.setEnabled(true);
        }
        else{
            txt_descripcion.setEnabled(false);
        }

        txt_descripcion.setText("");

    }//GEN-LAST:event_check_descripcionActionPerformed

    private void bot_exportarexcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_exportarexcelActionPerformed
        String nombre_archivo;
        
        nombre_archivo = "C:/Documentos_Sistock/Estadistica_stock.xls";
        
        
        reporte_excel ex = new reporte_excel(new File(nombre_archivo), "DATOS EN STOCK Y USADO", tabla_resumen);
        
        
        try {
            if(ex.excel_export_reporte()){
                
                    File archivo_abrir = new File(nombre_archivo);
                    Desktop.getDesktop().open(archivo_abrir);
                
            }
            else{
                JOptionPane.showMessageDialog(null, "ERROR EN EXPORTAR ARCHIVO EXCEL");
            }
        } catch (IOException | WriteException ex1) {
            JOptionPane.showMessageDialog(null, "ERROR ABRIR ARCHIVO");
        }
        
        
        
    }//GEN-LAST:event_bot_exportarexcelActionPerformed

    private void cmb_centrocostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_centrocostoActionPerformed
        String sql;
        
        if(evt.getModifiers()!=0){
            sql="SELECT id_equipo,equipo FROM tbl_equipo WHERE fk_centrocosto = " + Integer.parseInt(cmb_centrocosto.getSelectedItem().toString().substring(0, 6).trim()) + ";"; 
            cmb_equipo = funciones.cargar_combo(cmb_equipo,sql,"Seleccione...");
        }
        
    }//GEN-LAST:event_cmb_centrocostoActionPerformed

    private void chk_equipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_equipoActionPerformed
         if (chk_equipo.isSelected()){
            cmb_equipo.setEnabled(true);
        }
        else{
            cmb_equipo.setEnabled(false);         
        }
    }//GEN-LAST:event_chk_equipoActionPerformed

    private void txt_codigosapKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_codigosapKeyPressed
        if ( ( (evt.getKeyCode() >= 48 ) && (evt.getKeyCode() <= 57 ) ) || ( (evt.getKeyCode() >= 37 ) && (evt.getKeyCode() <= 40 ) ) || ((evt.getKeyCode() >= 96 ) && (evt.getKeyCode() <= 105 )) || (evt.getKeyCode() == 144) || (evt.getKeyCode() == 127) || (evt.getKeyCode() == 8)  || (evt.getKeyCode() == 10)){       
        }
        else{
            JOptionPane.showMessageDialog(null, "CARACTER NO VALIDO. SOLO NÚMEROS (1..9)", "SISTOCK - VER STOCK", JOptionPane.ERROR_MESSAGE,null);
            txt_codigosap.setText("");
             
        }
    }//GEN-LAST:event_txt_codigosapKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_verstockimp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_verstockimp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_verstockimp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_verstockimp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_verstockimp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bot_buscar;
    private javax.swing.JButton bot_cerrar;
    private javax.swing.JButton bot_exportarexcel;
    private javax.swing.JButton bot_limpiar;
    private javax.swing.JCheckBox check_area;
    private javax.swing.JCheckBox check_codsap;
    private javax.swing.JCheckBox check_descripcion;
    private javax.swing.JCheckBox check_fecha;
    private javax.swing.JCheckBox chk_equipo;
    private javax.swing.JComboBox<String> cmb_centrocosto;
    private javax.swing.JComboBox<String> cmb_equipo;
    private com.toedter.calendar.JDateChooser date_desde;
    private com.toedter.calendar.JDateChooser date_hasta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbl_desde;
    private javax.swing.JLabel lbl_hasta;
    private javax.swing.JLabel lbl_stock;
    private javax.swing.JTable tabla_resumen;
    private javax.swing.JTable tabla_stockreporte;
    private javax.swing.JTable table_stock;
    private javax.swing.JTable table_usado;
    private javax.swing.JTextField txt_codigosap;
    private javax.swing.JTextField txt_descripcion;
    // End of variables declaration//GEN-END:variables
}
