/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistock;

import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ruben
 */
public class frm_estatusregistropkf extends javax.swing.JFrame {

    /**
     * Creates new form frm_estatusregistropkf
     */
    public frm_estatusregistropkf() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.WHITE);
        this.setTitle("SISTOCK - CONSULTAR ESTATUS STOCK");
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_encabezado = new javax.swing.JLabel();
        RESUMEN = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_pkf = new javax.swing.JTable();
        bot_excel = new javax.swing.JButton();
        bot_limpiar = new javax.swing.JButton();
        bot_cerrar = new javax.swing.JButton();
        bot_buscar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        chk_fechasolicitud = new javax.swing.JCheckBox();
        chk_centrocosto = new javax.swing.JCheckBox();
        chk_equipo = new javax.swing.JCheckBox();
        chk_estatus = new javax.swing.JCheckBox();
        date_desde = new com.toedter.calendar.JDateChooser();
        date_hasta = new com.toedter.calendar.JDateChooser();
        cmb_centrocosto = new javax.swing.JComboBox();
        cmb_equipo = new javax.swing.JComboBox();
        cmb_estatus = new javax.swing.JComboBox<>();
        lbl_desde = new javax.swing.JLabel();
        lbl_hasta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_encabezado.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbl_encabezado.setForeground(new java.awt.Color(0, 0, 255));
        lbl_encabezado.setText("REGISTRO DE SERVICIOS TALLER CENTRAL PKF");
        getContentPane().add(lbl_encabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        RESUMEN.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        RESUMEN.setForeground(new java.awt.Color(0, 0, 255));
        RESUMEN.setText("RESUMEN");
        getContentPane().add(RESUMEN, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, -1, -1));

        tabla_pkf.setBackground(new java.awt.Color(240, 255, 255));
        tabla_pkf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tabla_pkf.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "FECHA SOLICITUD", "EQUIPO", "FALLA", "SERVICIO PKF", "REALIZADO POR", "COSTO SERVICIO", "COSTO HORA", "FECHA SERVICIO", "AREA", "ESTATUS", "OBSERVACIONES", "DURACION EN DIAS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla_pkf);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 1330, 320));

        bot_excel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bot_excel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/excel.png"))); // NOI18N
        bot_excel.setText("EXPORTAR A EXCEL");
        bot_excel.setToolTipText("");
        bot_excel.setEnabled(false);
        bot_excel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_excelActionPerformed(evt);
            }
        });
        getContentPane().add(bot_excel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 620, -1, -1));

        bot_limpiar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bot_limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eraser.png"))); // NOI18N
        bot_limpiar.setText("REINICIAR");
        bot_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_limpiarActionPerformed(evt);
            }
        });
        getContentPane().add(bot_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 620, -1, -1));

        bot_cerrar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bot_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/close.png"))); // NOI18N
        bot_cerrar.setText("CERRAR");
        bot_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_cerrarActionPerformed(evt);
            }
        });
        getContentPane().add(bot_cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 620, -1, -1));

        bot_buscar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bot_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Search.png"))); // NOI18N
        bot_buscar.setText("BUSCAR");
        bot_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_buscarActionPerformed(evt);
            }
        });
        getContentPane().add(bot_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 100, 180, 50));

        jPanel1.setBackground(new java.awt.Color(240, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chk_fechasolicitud.setBackground(new java.awt.Color(240, 255, 255));
        chk_fechasolicitud.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        chk_fechasolicitud.setSelected(true);
        chk_fechasolicitud.setText("FECHA SOLICITUD");
        chk_fechasolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_fechasolicitudActionPerformed(evt);
            }
        });
        jPanel1.add(chk_fechasolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        chk_centrocosto.setBackground(new java.awt.Color(240, 255, 255));
        chk_centrocosto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        chk_centrocosto.setText("CENTRO DE COSTO");
        chk_centrocosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_centrocostoActionPerformed(evt);
            }
        });
        jPanel1.add(chk_centrocosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        chk_equipo.setBackground(new java.awt.Color(240, 255, 255));
        chk_equipo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        chk_equipo.setText("EQUIPO");
        chk_equipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_equipoActionPerformed(evt);
            }
        });
        jPanel1.add(chk_equipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        chk_estatus.setBackground(new java.awt.Color(240, 255, 255));
        chk_estatus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        chk_estatus.setText("ESTATUS");
        chk_estatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_estatusActionPerformed(evt);
            }
        });
        jPanel1.add(chk_estatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        date_desde.setBackground(new java.awt.Color(240, 255, 255));
        date_desde.setDateFormatString("d/MM/yyyy");
        date_desde.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(date_desde, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 160, 30));

        date_hasta.setBackground(new java.awt.Color(240, 255, 255));
        date_hasta.setDateFormatString("d/MM/yyyy");
        date_hasta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(date_hasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 160, 30));

        cmb_centrocosto.setBackground(new java.awt.Color(240, 255, 255));
        cmb_centrocosto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmb_centrocosto.setEnabled(false);
        jPanel1.add(cmb_centrocosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 330, 30));

        cmb_equipo.setBackground(new java.awt.Color(240, 255, 255));
        cmb_equipo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmb_equipo.setEnabled(false);
        jPanel1.add(cmb_equipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 330, 30));

        cmb_estatus.setBackground(new java.awt.Color(240, 255, 255));
        cmb_estatus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmb_estatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "PENDIENTE", "EJECUTADO" }));
        cmb_estatus.setEnabled(false);
        jPanel1.add(cmb_estatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 230, 30));

        lbl_desde.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_desde.setText("Desde");
        jPanel1.add(lbl_desde, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        lbl_hasta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_hasta.setText("Hasta");
        jPanel1.add(lbl_hasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 630, 190));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        String sql;
        
        sql="SELECT id_centrocosto,centrocosto FROM tbl_centrocosto;"; 
        cmb_centrocosto = funciones.cargar_combo(cmb_centrocosto,sql,"Seleccione...");
        sql="SELECT id_equipo,equipo FROM tbl_equipo;"; 
        cmb_equipo = funciones.cargar_combo(cmb_equipo,sql,"Seleccione...");
    }//GEN-LAST:event_formWindowOpened

    private void bot_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_cerrarActionPerformed
       this.dispose();
    }//GEN-LAST:event_bot_cerrarActionPerformed

    private void bot_excelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_excelActionPerformed
        String nombre_archivo;
        
        nombre_archivo = "C:/Documentos_Sistock/Estadistica_pkf.xls";
        
        
        reporte_excel ex = new reporte_excel(new File(nombre_archivo), "INFORME ESTATUS TALLER PKF", tabla_pkf);
        
        
        if(ex.excel_pkf_export()){
            try{
                 File archivo_abrir = new File(nombre_archivo);
                 Desktop.getDesktop().open(archivo_abrir);
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, "ERROR ABRIR ARCHIVO");
         
            }
        }
        else{
                JOptionPane.showMessageDialog(null, "ERROR EN EXPORTAR ARCHIVO EXCEL");
        }      
    }//GEN-LAST:event_bot_excelActionPerformed

    private void bot_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_buscarActionPerformed
        Integer centrocosto=0;
        Integer equipo=0;
        Boolean opcion = false;
        String estatus = "Seleccione...";
        String fechadesde = "";
        String fechahasta = "";
        
        if(chk_equipo.isSelected()){
            opcion = true;
            equipo = Integer.parseInt(cmb_equipo.getSelectedItem().toString().substring(0, 3).trim());
        }
        
        if(chk_centrocosto.isSelected()){
            opcion = true;
            centrocosto = Integer.parseInt(cmb_centrocosto.getSelectedItem().toString().substring(0, 6).trim());
        }
        
       
        if(chk_estatus.isSelected()){
            opcion = true;
            estatus = cmb_estatus.getSelectedItem().toString().trim();
        }
        
       
        if(chk_fechasolicitud.isSelected()){
            fechadesde =  funciones.fecha_convertir_date(date_desde, 1);
            fechahasta = funciones.fecha_convertir_date(date_hasta, 1);
            System.out.println(fechadesde);
            System.out.println(fechahasta);
            if (!fechadesde.equals("") && !fechahasta.equals("")){
                opcion = true;
            }
           
        }   
       
        
        if (opcion){
            
            
            taller ta = new taller(equipo,
                                    centrocosto,
                                    estatus,
                                    fechadesde,
                                    fechahasta,
                                    tabla_pkf,4
                                  );
            try {
                if(ta.consultarestatustaller()){
                    if (tabla_pkf.getRowCount() > 0){
                        tabla_pkf.setDefaultRenderer(Object.class, new RenderTablaEstatus());
                        bot_excel.setEnabled(true);
                    }    
                    else{
                        bot_excel.setEnabled(false);
                        JOptionPane.showMessageDialog(null, "NO HAY DATOS PARA LA CONSULTA SELECCIONADA");
                    }
                }
            } catch (ParseException ex) {
                Logger.getLogger(frm_estatusregistropkf.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            
            JOptionPane.showMessageDialog(null, "SELECCIONE ALGUNO DE LAS OPCIONES PARA REALIZAR LA CONSULTA");
        }
    }//GEN-LAST:event_bot_buscarActionPerformed

    private void chk_fechasolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_fechasolicitudActionPerformed
        if (chk_fechasolicitud.isSelected()){ 
            bot_buscar.setEnabled(true);
            date_desde.setEnabled(true);
            date_hasta.setEnabled(true);
        }    
        else{
            date_desde.setEnabled(false);
            date_hasta.setEnabled(false);
        }    
    }//GEN-LAST:event_chk_fechasolicitudActionPerformed

    private void chk_centrocostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_centrocostoActionPerformed
        if (chk_centrocosto.isSelected()){ 
            bot_buscar.setEnabled(true);
            cmb_centrocosto.setEnabled(true);
        }    
        else{
            cmb_centrocosto.setEnabled(false);
        }    
    }//GEN-LAST:event_chk_centrocostoActionPerformed

    private void chk_equipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_equipoActionPerformed
        if (chk_equipo.isSelected()){ 
            bot_buscar.setEnabled(true);
            cmb_equipo.setEnabled(true);
        }    
        else{
            cmb_equipo.setEnabled(false);
        }  
    }//GEN-LAST:event_chk_equipoActionPerformed

    private void chk_estatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_estatusActionPerformed
         if (chk_estatus.isSelected()){ 
            cmb_estatus.setEnabled(true);
        }    
        else{
            cmb_estatus.setEnabled(false);
        }  
    }//GEN-LAST:event_chk_estatusActionPerformed

    private void bot_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_limpiarActionPerformed
        frm_estatusregistropkf frm = new frm_estatusregistropkf();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bot_limpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_estatusregistropkf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_estatusregistropkf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_estatusregistropkf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_estatusregistropkf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_estatusregistropkf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RESUMEN;
    private javax.swing.JButton bot_buscar;
    private javax.swing.JButton bot_cerrar;
    private javax.swing.JButton bot_excel;
    private javax.swing.JButton bot_limpiar;
    private javax.swing.JCheckBox chk_centrocosto;
    private javax.swing.JCheckBox chk_equipo;
    private javax.swing.JCheckBox chk_estatus;
    private javax.swing.JCheckBox chk_fechasolicitud;
    private javax.swing.JComboBox cmb_centrocosto;
    private javax.swing.JComboBox cmb_equipo;
    private javax.swing.JComboBox<String> cmb_estatus;
    private com.toedter.calendar.JDateChooser date_desde;
    private com.toedter.calendar.JDateChooser date_hasta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_desde;
    private javax.swing.JLabel lbl_encabezado;
    private javax.swing.JLabel lbl_hasta;
    private javax.swing.JTable tabla_pkf;
    // End of variables declaration//GEN-END:variables
}
