/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sistock;


import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class frm_usuario extends javax.swing.JFrame {

    public frm_usuario() {
        initComponents();
        this.setTitle("SISTOCK - USUARIOS");
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.WHITE);
        this.setExtendedState(MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_cedula = new javax.swing.JLabel();
        lbl_login = new javax.swing.JLabel();
        lbl_password = new javax.swing.JLabel();
        txt_cedula = new javax.swing.JTextField();
        txt_nombres = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        lbl_confirmar = new javax.swing.JLabel();
        txt_confirmar = new javax.swing.JPasswordField();
        bot_buscar = new javax.swing.JButton();
        bot_guardar = new javax.swing.JButton();
        bot_cerrar = new javax.swing.JButton();
        bot_actualizar = new javax.swing.JButton();
        bot_baja = new javax.swing.JButton();
        bot_alta = new javax.swing.JButton();
        bot_limpiar = new javax.swing.JButton();
        radio_nivel1 = new javax.swing.JRadioButton();
        radio_nivel2 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        lbl_nombres = new javax.swing.JLabel();
        txt_login = new javax.swing.JTextField();
        lbl_etiqueta = new javax.swing.JLabel();
        lbl_plantilla = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GESTIONAC - ACTUALIZAR USUARIO");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_cedula.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_cedula.setText("CÉDULA");
        getContentPane().add(lbl_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, -1, -1));

        lbl_login.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_login.setText("USUARIO");
        getContentPane().add(lbl_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, -1, -1));

        lbl_password.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_password.setText("PASSWORD");
        getContentPane().add(lbl_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, -1, -1));

        txt_cedula.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_cedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_cedulaKeyPressed(evt);
            }
        });
        getContentPane().add(txt_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, 200, -1));

        txt_nombres.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_nombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nombresKeyPressed(evt);
            }
        });
        getContentPane().add(txt_nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 440, -1));

        txt_password.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_passwordKeyPressed(evt);
            }
        });
        getContentPane().add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, 280, -1));

        lbl_confirmar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_confirmar.setText("CONFIRMAR");
        getContentPane().add(lbl_confirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, -1, -1));

        txt_confirmar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_confirmar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_confirmarKeyPressed(evt);
            }
        });
        getContentPane().add(txt_confirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, 280, -1));

        bot_buscar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bot_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Search.png"))); // NOI18N
        bot_buscar.setText("Buscar");
        bot_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_buscarActionPerformed(evt);
            }
        });
        bot_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bot_buscarKeyPressed(evt);
            }
        });
        getContentPane().add(bot_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 110, -1, -1));

        bot_guardar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bot_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/databasesave.png"))); // NOI18N
        bot_guardar.setText("GUARDAR");
        bot_guardar.setEnabled(false);
        bot_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_guardarActionPerformed(evt);
            }
        });
        bot_guardar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bot_guardarKeyPressed(evt);
            }
        });
        getContentPane().add(bot_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 570, -1, -1));

        bot_cerrar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bot_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/close.png"))); // NOI18N
        bot_cerrar.setText("CERRAR");
        bot_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_cerrarActionPerformed(evt);
            }
        });
        bot_cerrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bot_cerrarKeyPressed(evt);
            }
        });
        getContentPane().add(bot_cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 650, 170, -1));

        bot_actualizar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bot_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/refresh.png"))); // NOI18N
        bot_actualizar.setText("ACTUALIZAR");
        bot_actualizar.setEnabled(false);
        bot_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_actualizarActionPerformed(evt);
            }
        });
        bot_actualizar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bot_actualizarKeyPressed(evt);
            }
        });
        getContentPane().add(bot_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 570, -1, -1));

        bot_baja.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bot_baja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/darbaja.png"))); // NOI18N
        bot_baja.setText("DAR BAJA");
        bot_baja.setEnabled(false);
        bot_baja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_bajaActionPerformed(evt);
            }
        });
        bot_baja.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bot_bajaKeyPressed(evt);
            }
        });
        getContentPane().add(bot_baja, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 570, -1, -1));

        bot_alta.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bot_alta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/daralta.png"))); // NOI18N
        bot_alta.setText("DAR ALTA");
        bot_alta.setEnabled(false);
        bot_alta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_altaActionPerformed(evt);
            }
        });
        bot_alta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bot_altaKeyPressed(evt);
            }
        });
        getContentPane().add(bot_alta, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 570, -1, -1));

        bot_limpiar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bot_limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eraser.png"))); // NOI18N
        bot_limpiar.setText("REINICIAR");
        bot_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_limpiarActionPerformed(evt);
            }
        });
        bot_limpiar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bot_limpiarKeyPressed(evt);
            }
        });
        getContentPane().add(bot_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 650, -1, -1));

        radio_nivel1.setBackground(new java.awt.Color(255, 255, 255));
        radio_nivel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        radio_nivel1.setText("ADMINISTRADOR");
        radio_nivel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radio_nivel1MouseClicked(evt);
            }
        });
        radio_nivel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_nivel1ActionPerformed(evt);
            }
        });
        getContentPane().add(radio_nivel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 470, -1, -1));

        radio_nivel2.setBackground(new java.awt.Color(255, 255, 255));
        radio_nivel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        radio_nivel2.setSelected(true);
        radio_nivel2.setText("INVITADO");
        radio_nivel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radio_nivel2MouseClicked(evt);
            }
        });
        radio_nivel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_nivel2ActionPerformed(evt);
            }
        });
        getContentPane().add(radio_nivel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 470, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("PRIVILEGIO EN EL SISTEMA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, -1, -1));

        lbl_nombres.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_nombres.setText("NOMBRES");
        getContentPane().add(lbl_nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, -1, -1));

        txt_login.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_login.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_loginKeyPressed(evt);
            }
        });
        getContentPane().add(txt_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, 280, -1));

        lbl_etiqueta.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbl_etiqueta.setForeground(new java.awt.Color(0, 0, 255));
        lbl_etiqueta.setText("MÓDULO USUARIO");
        getContentPane().add(lbl_etiqueta, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, -1, -1));

        lbl_plantilla.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_plantilla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/PLANTILLA_1.jpg"))); // NOI18N
        getContentPane().add(lbl_plantilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bot_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_buscarActionPerformed
        
        String sql;
        boolean resp;
        String tmp;

        sql = "select a.cedula,a.nombres,a.usuario,a.contrasena,a.status,a.nivel from tbl_usuario a where a.cedula = ";
        
        if (!txt_cedula.getText().equals("")){

            usuario us = new usuario(Integer.parseInt(txt_cedula.getText().trim()),sql);

            resp = us.buscar_cedula_usuario();

            if (resp){

                txt_cedula.setText(String.valueOf(us.getcedula()));
                txt_nombres.setText(String.valueOf(us.getNombres()));
                txt_login.setText(us.getusuario()) ;
                txt_password.setText(String.valueOf(us.getpassword()));
                txt_confirmar.setText(String.valueOf(us.getpassword()));

                if (us.getnivel().equals(1)){
                    radio_nivel1.setSelected(true);
                    radio_nivel2.setSelected(false);
                }
                else{
                    radio_nivel2.setSelected(true);
                    radio_nivel1.setSelected(false);
                }

                bot_guardar.setEnabled(false);
                
                if (us.getstatus()){
                    bot_baja.setEnabled(true);
                    bot_alta.setEnabled(false);
                    txt_nombres.setEnabled(true);
                    txt_login.setEnabled(true);
                    txt_password.setEnabled(true);
                    txt_confirmar.setEnabled(true);
                    bot_actualizar.setEnabled(true);
                    radio_nivel1.setEnabled(true);
                    radio_nivel2.setEnabled(true);
                }
                else{

                    txt_cedula.setEnabled(false);
                    txt_nombres.setEnabled(false);
                    txt_login.setEnabled(false);
                    txt_password.setEnabled(false);
                    txt_confirmar.setEnabled(false);
                    bot_actualizar.setEnabled(false);    
                    bot_baja.setEnabled(false);
                    bot_alta.setEnabled(true);
                    radio_nivel1.setEnabled(false);
                    radio_nivel2.setEnabled(false);
                }
            }
            else{
                //tmp= txt_cedula.getText();
                //bot_limpiar.doClick();
                //txt_cedula.setText(tmp);
                txt_nombres.requestFocusInWindow();
                bot_guardar.setEnabled(true);
            }

        }

    }//GEN-LAST:event_bot_buscarActionPerformed

    private void bot_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_cerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_bot_cerrarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        txt_cedula.requestFocusInWindow();
    }//GEN-LAST:event_formWindowOpened

    private void bot_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_limpiarActionPerformed
       frm_usuario frm = new frm_usuario();
       frm.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_bot_limpiarActionPerformed

    private void txt_cedulaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cedulaKeyPressed
        if (evt.getKeyCode()==10){
            bot_buscar.doClick();
        }
        
        if ( ( (evt.getKeyCode() >= 48 ) && (evt.getKeyCode() <= 57 ) ) || ( (evt.getKeyCode() >= 37 ) && (evt.getKeyCode() <= 40 ) ) || ((evt.getKeyCode() >= 96 ) && (evt.getKeyCode() <= 105 )) || (evt.getKeyCode() == 144) || (evt.getKeyCode() == 127) || (evt.getKeyCode() == 8)  || (evt.getKeyCode() == 10)){       
        }
        else{
             if (evt.getKeyCode() == 27){
         
                    bot_limpiar.doClick();
                    
             }
             else{
                JOptionPane.showMessageDialog(null, "CARACTER NO VALIDO. SOLO NÚMEROS (1..9)", "SISTOCK - USUARIO", JOptionPane.ERROR_MESSAGE,null);
                txt_cedula.setText("");
             }   
        }

    }//GEN-LAST:event_txt_cedulaKeyPressed

    private void bot_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_guardarActionPerformed
 
        String sql;
        boolean resp;
        String password = new String(txt_password.getPassword());
        String confirm_password = new String(txt_confirmar.getPassword());
        Integer nivel = 2;
        
        if(!txt_cedula.getText().equals("") && !txt_nombres.getText().equals("") && !txt_login.getText().equals("") && !txt_password.getPassword().equals("") && !txt_confirmar.getPassword().equals("") ) {
            
            if (password.equals(confirm_password)){
                
                if (radio_nivel1.isSelected()){
                    nivel = 1;
                }
                else{
                    nivel = 2;
                }
                    
                
                sql = "insert into tbl_usuario values(";

                usuario us = new usuario(Integer.parseInt(txt_cedula.getText().trim()),txt_nombres.getText().trim(),txt_login.getText().trim(),confirm_password,nivel,true,sql);

                resp = us.actualizar_usuario();

                if (resp){
                    bot_baja.setEnabled(true);
                    bot_alta.setEnabled(false);
                    bot_guardar.setEnabled(false);
                    bot_actualizar.setEnabled(true);
                    bot_limpiar.setEnabled(true);
                }
            }
            else{
                 JOptionPane.showMessageDialog(null,"ERROR. NO HAY COINCIDENCIA EN EL PASSWORD");
            }
        }
        else{

            JOptionPane.showMessageDialog(null,"DATOS INCOMPLETOS PARA GUARDAR");
        }
    }//GEN-LAST:event_bot_guardarActionPerformed

    private void bot_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_actualizarActionPerformed

        boolean resp;
        String sql;
        Integer nivel = 2;
        String password = new String(txt_password.getPassword());
        String confirm_password = new String(txt_confirmar.getPassword());
 
        
        if(!txt_cedula.getText().equals("") && !txt_nombres.getText().equals("") && !txt_nombres.getText().equals("") && !txt_password.getPassword().equals("") && !txt_confirmar.getPassword().equals("") ) {

            if (password.equals(confirm_password)){
            
                if (radio_nivel1.isSelected()){
                    nivel = 1;
                }
                else{
                    nivel = 2;
                }
              
            
                sql = "update tbl_usuario set contrasena = ";

                usuario us = new usuario(Integer.parseInt(txt_cedula.getText().trim()),txt_nombres.getText().trim().toUpperCase(),txt_login.getText().trim(),confirm_password,nivel,true,sql);

                resp = us.actualizar_usuario_detalle();

                if (resp){
                    bot_alta.setEnabled(false);
                }
            }
            else{
                 JOptionPane.showMessageDialog(null,"ERROR. NO HAY COINCIDENCIA EN EL PASSWORD");
            }    
        }
        else{

            JOptionPane.showMessageDialog(null,"DATOS INCOMPLETOS PARA ACTUALIZAR");
        }
    }//GEN-LAST:event_bot_actualizarActionPerformed

    private void bot_bajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_bajaActionPerformed
        String sql;
        boolean resp;

        sql = "update tbl_usuario set status = false where cedula = ";

        txt_login.setEnabled(false);
        txt_nombres.setEnabled(false);
        txt_password.setEnabled(false);
        txt_confirmar.setEnabled(false);
        
        usuario us = new usuario(Integer.parseInt(txt_cedula.getText().trim()),sql);

        resp = us.actualizar_usuario_status();

        if (resp){
            bot_baja.setEnabled(false);
            bot_alta.setEnabled(true);
            bot_actualizar.setEnabled(false);
            bot_guardar.setEnabled(false);
            bot_limpiar.setEnabled(true);
            radio_nivel1.setEnabled(false);
            radio_nivel2.setEnabled(false);
        }
    }//GEN-LAST:event_bot_bajaActionPerformed

    private void bot_altaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_altaActionPerformed
        String sql;
        boolean resp;

        sql = "update tbl_usuario set status = true where cedula = ";

        txt_login.setEnabled(true);
        txt_nombres.setEnabled(true);
        txt_password.setEnabled(true);
        txt_confirmar.setEnabled(true);
    
        usuario us = new usuario(Integer.parseInt(txt_cedula.getText().trim()),sql);

        resp = us.actualizar_usuario_status();

        if (resp){
            bot_baja.setEnabled(true);
            bot_alta.setEnabled(false);
            bot_actualizar.setEnabled(true);
            bot_guardar.setEnabled(false);
            bot_limpiar.setEnabled(true);
            radio_nivel1.setEnabled(true);
            radio_nivel2.setEnabled(true);

        }
    }//GEN-LAST:event_bot_altaActionPerformed

    private void bot_buscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bot_buscarKeyPressed
                if (evt.getKeyCode() == 27){
         
                    bot_limpiar.doClick();
                    
                }
       
    }//GEN-LAST:event_bot_buscarKeyPressed

    private void txt_passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passwordKeyPressed
                if (evt.getKeyCode() == 27){
         
                    bot_limpiar.doClick();
                    
                }
        
    }//GEN-LAST:event_txt_passwordKeyPressed

    private void txt_confirmarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_confirmarKeyPressed
                if (evt.getKeyCode() == 27){
         
                    bot_limpiar.doClick();
                    
                }
    
    }//GEN-LAST:event_txt_confirmarKeyPressed

    private void bot_guardarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bot_guardarKeyPressed
                if (evt.getKeyCode() == 27){
         
                    bot_limpiar.doClick();
                    
                }
       
    }//GEN-LAST:event_bot_guardarKeyPressed

    private void bot_actualizarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bot_actualizarKeyPressed
                if (evt.getKeyCode() == 27){
         
                    bot_limpiar.doClick();
                    
                }
      
    }//GEN-LAST:event_bot_actualizarKeyPressed

    private void bot_bajaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bot_bajaKeyPressed
                if (evt.getKeyCode() == 27){
         
                    bot_limpiar.doClick();
                    
                }
       
    }//GEN-LAST:event_bot_bajaKeyPressed

    private void bot_altaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bot_altaKeyPressed
                if (evt.getKeyCode() == 27){
         
                    bot_limpiar.doClick();
                    
                }
        
    }//GEN-LAST:event_bot_altaKeyPressed

    private void bot_limpiarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bot_limpiarKeyPressed
                if (evt.getKeyCode() == 27){
         
                    bot_limpiar.doClick();
                    
                }
      
    }//GEN-LAST:event_bot_limpiarKeyPressed

    private void bot_cerrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bot_cerrarKeyPressed
                if (evt.getKeyCode() == 27){
         
                    bot_limpiar.doClick();
                    
                }
        
    }//GEN-LAST:event_bot_cerrarKeyPressed

    private void radio_nivel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radio_nivel1MouseClicked
        radio_nivel2.setSelected(false);
    }//GEN-LAST:event_radio_nivel1MouseClicked

    private void radio_nivel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radio_nivel2MouseClicked
        radio_nivel1.setSelected(false);    
    }//GEN-LAST:event_radio_nivel2MouseClicked

    private void txt_loginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_loginKeyPressed
       
    }//GEN-LAST:event_txt_loginKeyPressed

    private void txt_nombresKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombresKeyPressed
       if (evt.getKeyCode()==10){
            bot_buscar.doClick();
        }
        
        if ( ( (evt.getKeyCode() >= 63 ) && (evt.getKeyCode() <= 90 ) ) || ( (evt.getKeyCode() >= 37 ) && (evt.getKeyCode() <= 40 ) ) || (evt.getKeyCode() == 0 ) || (evt.getKeyCode() == 8 ) || (evt.getKeyCode() == 32 )){       
        }
        else{
             if (evt.getKeyCode() == 27){
         
                    bot_limpiar.doClick();
                    
             }
             else{
                JOptionPane.showMessageDialog(null, "CARACTER NO VALIDO. SOLO LETRAS (A..Z)", "SISBAL - USUARIO", JOptionPane.ERROR_MESSAGE,null);
                txt_nombres.setText("");
             }   
        }
    }//GEN-LAST:event_txt_nombresKeyPressed

    private void radio_nivel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_nivel2ActionPerformed
       radio_nivel1.setSelected(false);
    }//GEN-LAST:event_radio_nivel2ActionPerformed

    private void radio_nivel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_nivel1ActionPerformed
       radio_nivel2.setSelected(false);
    }//GEN-LAST:event_radio_nivel1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel            0                                                                                                                                              00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000                                   00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 0*/
         //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the for                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000                                                                                                                                                                                                                                                                                                                                                                    m */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_usuario().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton bot_actualizar;
    private static javax.swing.JButton bot_alta;
    private static javax.swing.JButton bot_baja;
    private static javax.swing.JButton bot_buscar;
    private static javax.swing.JButton bot_cerrar;
    private static javax.swing.JButton bot_guardar;
    private static javax.swing.JButton bot_limpiar;
    private javax.swing.JLabel jLabel2;
    private static javax.swing.JLabel lbl_cedula;
    private javax.swing.JLabel lbl_confirmar;
    private javax.swing.JLabel lbl_etiqueta;
    private static javax.swing.JLabel lbl_login;
    private javax.swing.JLabel lbl_nombres;
    private static javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_plantilla;
    private static javax.swing.JRadioButton radio_nivel1;
    private static javax.swing.JRadioButton radio_nivel2;
    private static javax.swing.JTextField txt_cedula;
    private static javax.swing.JPasswordField txt_confirmar;
    private static javax.swing.JTextField txt_login;
    private static javax.swing.JTextField txt_nombres;
    private static javax.swing.JPasswordField txt_password;
    // End of variables declaration//GEN-END:variables
}
